import { QuestionInput } from "@/types/question";

export const EXPANDED_MATH_QUESTIONS: QuestionInput[] = [
  // =========================================================================
  // 1. REAL NUMBERS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If the HCF of 65 and 117 is expressible in the form 65m - 117, then the value of m is:",
    options: ["A) 4", "B) 2", "C) 1", "D) 3"],
    answer: "B) 2",
    explanation: "Using prime factorisation: 65 = 5 × 13 and 117 = 3² × 13. Therefore, HCF(65, 117) = 13. Given 65m - 117 = 13 => 65m = 130 => m = 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the largest number which divides 70 and 125, leaving remainders 5 and 8 respectively.",
    options: null,
    answer: "13",
    explanation: "The required number is HCF(70 - 5, 125 - 8) = HCF(65, 117). 65 = 5 × 13, 117 = 3² × 13. Hence HCF = 13.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The decimal expansion of the rational number 14587 / (1250) will terminate after how many decimal places?",
    options: ["A) 1", "B) 2", "C) 3", "D) 4"],
    answer: "D) 4",
    explanation: "1250 = 2¹ × 5⁴. The maximum exponent among 2 and 5 in the denominator is 4, so the decimal expansion terminates after 4 decimal places.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove that √3 + √5 is an irrational number.",
    options: null,
    answer: "Let √3 + √5 = x be rational. Squaring gives (√3 + √5)² = x² => 3 + 5 + 2√15 = x² => √15 = (x² - 8)/2. Since x is rational, (x² - 8)/2 is rational, which means √15 is rational. This contradicts that 15 has no integer square root (√15 is irrational). Thus √3 + √5 is irrational.",
    explanation: "Proof by contradiction showing that the square of the sum implies √15 is rational, which contradicts the irrationality of surds.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find the HCF and LCM of 404 and 96 by prime factorisation method and verify that HCF × LCM = Product of the two given numbers.",
    options: null,
    answer: "HCF = 4, LCM = 9696. Verification: 4 × 9696 = 38784, and 404 × 96 = 38784.",
    explanation: "404 = 2² × 101, 96 = 2⁵ × 3. HCF = 2² = 4. LCM = 2⁵ × 3 × 101 = 9696. HCF × LCM = 4 × 9696 = 38784. Product = 404 × 96 = 38784.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Three sets of English, Hindi and Mathematics books have to be stacked in such a way that all the books are stored topic-wise and the height of each stack is the same. The number of English books is 96, Hindi books is 240 and Mathematics books is 336. Assuming that the books are of the same thickness, determine the number of stacks of English, Hindi and Mathematics books.",
    options: null,
    answer: "Each stack contains 48 books. Number of English stacks = 2, Hindi stacks = 5, Mathematics stacks = 7. Total stacks = 14.",
    explanation: "HCF(96, 240, 336): 96 = 2⁵ × 3, 240 = 2⁴ × 3 × 5, 336 = 2⁴ × 3 × 7. HCF = 2⁴ × 3 = 48. English stacks = 96/48 = 2, Hindi stacks = 240/48 = 5, Math stacks = 336/48 = 7.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Show that the square of any positive integer cannot be of the form 5q + 2 or 5q + 3 for any integer q.",
    options: null,
    answer: "Any positive integer n is of the form 5m, 5m ± 1, or 5m ± 2. Squaring yields n² in the forms 5q, 5q + 1, or 5q + 4. Thus, n² can never be of the form 5q + 2 or 5q + 3.",
    explanation: "By Euclid's division lemma, n = 5m + r where r ∈ {0, 1, 2, 3, 4}. Evaluating n² in each case shows remainders modulo 5 can only be 0, 1, or 4.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If p and q are two distinct prime numbers, then their LCM is:",
    options: ["A) 1", "B) p / q", "C) p × q", "D) p + q"],
    answer: "C) p × q",
    explanation: "Since p and q have no common factors other than 1, HCF(p, q) = 1. Therefore, LCM(p, q) = (p × q) / HCF = p × q.",
  },

  // =========================================================================
  // 2. POLYNOMIALS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The number of zeroes that a polynomial of degree n can have is:",
    options: ["A) Exactly n", "B) At most n", "C) More than n", "D) At least n"],
    answer: "B) At most n",
    explanation: "By the Fundamental Theorem of Algebra, a real polynomial of degree n has at most n real zeroes.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the zeroes of the quadratic polynomial 4s² - 4s + 1 and verify the relationship between the zeroes and coefficients.",
    options: null,
    answer: "Zeroes are s = 1/2, 1/2. Sum of zeroes = 1/2 + 1/2 = 1 = -(-4)/4. Product of zeroes = (1/2)(1/2) = 1/4 = 1/4.",
    explanation: "4s² - 4s + 1 = (2s - 1)². Zeroes are s = 1/2, 1/2. Sum = 1 = -b/a. Product = 1/4 = c/a.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "If α and β are the zeroes of f(x) = x² - p(x + 1) - c, then (α + 1)(β + 1) is equal to:",
    options: ["A) c - 1", "B) 1 - c", "C) c", "D) 1 + c"],
    answer: "B) 1 - c",
    explanation: "f(x) = x² - px - (p + c). Here α + β = p and αβ = -(p + c). (α + 1)(β + 1) = αβ + (α + β) + 1 = -(p + c) + p + 1 = 1 - c.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If α and β are zeroes of the polynomial p(x) = 2x² + 5x + k such that α² + β² + αβ = 21/4, find the value of k.",
    options: null,
    answer: "k = 2",
    explanation: "α + β = -5/2, αβ = k/2. α² + β² + αβ = (α + β)² - αβ = (-5/2)² - k/2 = 25/4 - k/2. Set 25/4 - k/2 = 21/4 => k/2 = 4/4 = 1 => k = 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If the squared difference of the zeroes of the quadratic polynomial f(x) = x² + px + 45 is equal to 144, find the value of p.",
    options: null,
    answer: "p = ±18",
    explanation: "(α - β)² = (α + β)² - 4αβ = 144. Here α + β = -p and αβ = 45. So (-p)² - 4(45) = 144 => p² - 180 = 144 => p² = 324 => p = ±18.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "If α and β are the zeroes of the quadratic polynomial p(x) = 3x² - 4x + 1, form a quadratic polynomial whose zeroes are α²/β and β²/α.",
    options: null,
    answer: "9x² - 28x + 3 (or k(9x² - 28x + 3))",
    explanation: "α + β = 4/3, αβ = 1/3. New sum = α²/β + β²/α = (α³ + β³)/(αβ) = [(α+β)³ - 3αβ(α+β)]/(αβ) = [(64/27) - 3(1/3)(4/3)] / (1/3) = (28/27)/(1/3) = 28/9. New product = (α²/β)(β²/α) = αβ = 1/3. Polynomial = x² - (28/9)x + 1/3 = (9x² - 28x + 3)/9.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Find the zeroes of the polynomial f(x) = x³ - 5x² - 16x + 80, if its two zeroes are equal in magnitude but opposite in sign.",
    options: null,
    answer: "Zeroes are 4, -4, and 5.",
    explanation: "Let the zeroes be α, -α, and β. Sum of zeroes = α - α + β = 5 => β = 5. Product of zeroes = (α)(-α)(β) = -α²(5) = -80 => α² = 16 => α = 4. Hence zeroes are 4, -4, 5.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The graph of y = p(x) intersects the x-axis at 3 distinct points. The number of zeroes of p(x) is:",
    options: ["A) 0", "B) 1", "C) 2", "D) 3"],
    answer: "D) 3",
    explanation: "The number of real zeroes of y = p(x) equals the number of points where the graph intersects or touches the x-axis.",
  },

  // =========================================================================
  // 3. PAIR OF LINEAR EQUATIONS IN TWO VARIABLES (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The pair of equations x + 2y + 5 = 0 and -3x - 6y + 1 = 0 has:",
    options: ["A) A unique solution", "B) Exactly two solutions", "C) Infinitely many solutions", "D) No solution"],
    answer: "D) No solution",
    explanation: "a1/a2 = 1/(-3) = -1/3; b1/b2 = 2/(-6) = -1/3; c1/c2 = 5/1 = 5. Since a1/a2 = b1/b2 ≠ c1/c2, the lines are parallel and have no solution.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the values of x and y satisfying: x + y = 14 and x - y = 4.",
    options: null,
    answer: "x = 9, y = 5",
    explanation: "Adding both equations: 2x = 18 => x = 9. Substituting x = 9 in first equation: 9 + y = 14 => y = 5.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "For what value of k do the equations 3x - y + 8 = 0 and 6x - ky = -16 represent coincident lines?",
    options: ["A) 1/2", "B) -1/2", "C) 2", "D) -2"],
    answer: "C) 2",
    explanation: "6x - ky + 16 = 0. For coincident lines: a1/a2 = b1/b2 = c1/c2 => 3/6 = (-1)/(-k) = 8/16 => 1/2 = 1/k => k = 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Solve the following pair of linear equations by elimination method: 2x + 3y = 11 and 2x - 4y = -24. Hence find the value of m for which y = mx + 3.",
    options: null,
    answer: "x = -2, y = 5; m = -1",
    explanation: "Subtracting equations gives 7y = 35 => y = 5. Substituting in 2x + 15 = 11 => 2x = -4 => x = -2. Then 5 = m(-2) + 3 => -2m = 2 => m = -1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A fraction becomes 9/11 if 2 is added to both numerator and denominator. If 3 is added to both numerator and denominator it becomes 5/6. Find the fraction.",
    options: null,
    answer: "7/9",
    explanation: "Let fraction be x/y. (x+2)/(y+2) = 9/11 => 11x - 9y = -4. (x+3)/(y+3) = 5/6 => 6x - 5y = -3. Solving yields x = 7, y = 9. Fraction = 7/9.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A boat goes 30 km upstream and 44 km downstream in 10 hours. In 13 hours, it can go 40 km upstream and 55 km downstream. Determine the speed of the stream and that of the boat in still water.",
    options: null,
    answer: "Speed of boat in still water = 8 km/h; Speed of stream = 3 km/h.",
    explanation: "Let boat speed = x km/h, stream = y km/h. Let 1/(x-y) = u and 1/(x+y) = v. 30u + 44v = 10 and 40u + 55v = 13. Solving gives u = 1/5 and v = 1/11 => x - y = 5 and x + y = 11. Adding gives 2x = 16 => x = 8 km/h, y = 3 km/h.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Draw the graphs of the equations 5x - y = 5 and 3x - y = 3. Determine the coordinates of the vertices of the triangle formed by these lines and the y-axis, and calculate the area of the triangle.",
    options: null,
    answer: "Vertices: (1, 0), (0, -5), (0, -3). Area = 1 sq unit.",
    explanation: "Intersection of lines is (1, 0). Y-intercept of first line is (0, -5), of second is (0, -3). Base on y-axis = |-3 - (-5)| = 2 units. Height = x-coordinate = 1 unit. Area = (1/2) × 2 × 1 = 1 sq unit.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If x = a, y = b is the solution of the equations x - y = 2 and x + y = 4, then the values of a and b are respectively:",
    options: ["A) 3 and 5", "B) 5 and 3", "C) 3 and 1", "D) -1 and -3"],
    answer: "C) 3 and 1",
    explanation: "Adding gives 2x = 6 => x = 3 => a = 3. 3 + y = 4 => y = 1 => b = 1.",
  },

  // =========================================================================
  // 4. QUADRATIC EQUATIONS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The discriminant of the quadratic equation 2x² - 4x + 3 = 0 is:",
    options: ["A) -8", "B) 10", "C) -16", "D) 8"],
    answer: "A) -8",
    explanation: "D = b² - 4ac = (-4)² - 4(2)(3) = 16 - 24 = -8.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the roots of the quadratic equation x² - 3x - 10 = 0 by factorisation.",
    options: null,
    answer: "x = 5, x = -2",
    explanation: "x² - 5x + 2x - 10 = 0 => x(x - 5) + 2(x - 5) = 0 => (x - 5)(x + 2) = 0 => x = 5 or x = -2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "If the equation 9x² + 6kx + 4 = 0 has real and equal roots, then the value of k is:",
    options: ["A) 2 or -2", "B) 4 or -4", "C) 9 or -9", "D) 0"],
    answer: "A) 2 or -2",
    explanation: "For equal roots, D = 0 => (6k)² - 4(9)(4) = 0 => 36k² - 144 = 0 => k² = 4 => k = ±2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Solve for x: 1/(x + 4) - 1/(x - 7) = 11/30, where x ≠ -4, 7.",
    options: null,
    answer: "x = 1, x = 2",
    explanation: "[(x - 7) - (x + 4)] / [(x + 4)(x - 7)] = 11/30 => -11 / (x² - 3x - 28) = 11/30 => -(x² - 3x - 28) = 30 => x² - 3x + 2 = 0 => (x - 1)(x - 2) = 0 => x = 1, 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If the roots of the equation (b - c)x² + (c - a)x + (a - b) = 0 are equal, prove that 2b = a + c.",
    options: null,
    answer: "Proof: Notice that x = 1 satisfies the equation. For roots to be equal, both roots must be 1. Product of roots = (a - b)/(b - c) = 1 => a - b = b - c => 2b = a + c.",
    explanation: "Since sum of coefficients (b - c) + (c - a) + (a - b) = 0, x = 1 is a root. Since roots are equal, both roots are 1, meaning product = (a - b)/(b - c) = 1 => 2b = a + c.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Two water taps together can fill a tank in 9 3/8 hours (75/8 hours). The tap of larger diameter takes 10 hours less than the smaller one to fill the tank separately. Find the time in which each tap can separately fill the tank.",
    options: null,
    answer: "Smaller tap takes 25 hours; Larger tap takes 15 hours.",
    explanation: "Let smaller tap take x hours, larger takes (x - 10) hours. 1/x + 1/(x - 10) = 8/75 => (2x - 10)/(x² - 10x) = 8/75 => 75(2x - 10) = 8(x² - 10x) => 8x² - 230x + 750 = 0 => 4x² - 115x + 375 = 0 => (4x - 15)(x - 25) = 0. x = 25 (since x = 15/4 makes x - 10 negative). Smaller = 25 hrs, Larger = 15 hrs.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A motor boat whose speed is 18 km/h in still water takes 1 hour more to go 24 km upstream than to return downstream to the same spot. Find the speed of the stream.",
    options: null,
    answer: "Speed of the stream = 6 km/h",
    explanation: "Let stream speed = x km/h. Upstream speed = (18 - x), downstream = (18 + x). 24/(18 - x) - 24/(18 + x) = 1 => 24[18 + x - (18 - x)] / (324 - x²) = 1 => 48x = 324 - x² => x² + 48x - 324 = 0 => (x + 54)(x - 6) = 0 => x = 6 km/h.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following is a quadratic equation?",
    options: ["A) x² + 2x + 1 = (4 - x)² + 3", "B) -2x² = (5 - x)(2x - 2/5)", "C) (k + 1)x² + 3/2 x = 7, where k = -1", "D) x³ - x² = (x - 1)³"],
    answer: "D) x³ - x² = (x - 1)³",
    explanation: "Expanding (x - 1)³ gives x³ - 3x² + 3x - 1. So x³ - x² = x³ - 3x² + 3x - 1 => 2x² - 3x + 1 = 0, which is of degree 2.",
  },

  // =========================================================================
  // 5. ARITHMETIC PROGRESSIONS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The 10th term of the AP: 2, 7, 12, ... is:",
    options: ["A) 47", "B) 49", "C) 52", "D) 45"],
    answer: "A) 47",
    explanation: "a = 2, d = 7 - 2 = 5. a10 = a + 9d = 2 + 9(5) = 2 + 45 = 47.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the sum of the first 22 terms of the AP: 8, 3, -2, ...",
    options: null,
    answer: "-979",
    explanation: "a = 8, d = 3 - 8 = -5, n = 22. S22 = (22/2)[2(8) + (22 - 1)(-5)] = 11[16 - 105] = 11(-89) = -979.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "If the nth term of an AP is given by an = 3 + 4n, then the common difference d is:",
    options: ["A) 3", "B) 4", "C) 7", "D) 1"],
    answer: "B) 4",
    explanation: "a1 = 3 + 4(1) = 7, a2 = 3 + 4(2) = 11. Common difference d = a2 - a1 = 11 - 7 = 4.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "How many terms of the AP: 9, 17, 25, ... must be taken to give a sum of 636?",
    options: null,
    answer: "n = 12",
    explanation: "a = 9, d = 8, Sn = 636. (n/2)[2(9) + (n - 1)8] = 636 => n(18 + 8n - 8) = 1272 => 8n² + 10n - 1272 = 0 => 4n² + 5n - 636 = 0 => (4n + 53)(n - 12) = 0 => n = 12.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If the ratio of the sum of first n terms of two APs is (7n + 1) : (4n + 27), find the ratio of their 9th terms.",
    options: null,
    answer: "24 : 19",
    explanation: "Sn / S'n = (2a1 + (n-1)d1) / (2a2 + (n-1)d2) = (7n + 1)/(4n + 27). To find a9 / a'9 = (a1 + 8d1)/(a2 + 8d2), substitute n = 2(9) - 1 = 17. Ratio = [7(17) + 1] / [4(17) + 27] = (119 + 1)/(68 + 27) = 120/95 = 24/19.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A spiral is made up of successive semicircles, with centres alternately at A and B, starting with centre at A, of radii 0.5 cm, 1.0 cm, 1.5 cm, 2.0 cm, ... What is the total length of such a spiral made up of thirteen consecutive semicircles? (Take π = 22/7)",
    options: null,
    answer: "143 cm",
    explanation: "Lengths of semicircles form an AP: l1 = π(0.5), l2 = π(1.0), ..., l13 = π(6.5). Total length = π[0.5 + 1.0 + ... + 6.5] = (22/7) × (13/2)[0.5 + 6.5] = (22/7) × (13/2) × 7 = 11 × 13 = 143 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "If m times the mth term of an AP is equal to n times its nth term (m ≠ n), prove that the (m + n)th term of the AP is zero.",
    options: null,
    answer: "Proof: Given m[a + (m - 1)d] = n[a + (n - 1)d]. Rearranging gives a(m - n) + d(m² - n² - m + n) = 0 => (m - n)[a + (m + n - 1)d] = 0. Since m ≠ n, a + (m + n - 1)d = 0 => a_(m+n) = 0.",
    explanation: "Detailed algebraic proof factorising by (m - n) to directly deduce the standard formula for a_(m+n) equals zero.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In an AP, if d = -4, n = 7, and an = 4, then the first term a is:",
    options: ["A) 6", "B) 7", "C) 20", "D) 28"],
    answer: "D) 28",
    explanation: "an = a + (n - 1)d => 4 = a + (7 - 1)(-4) => 4 = a - 24 => a = 28.",
  },

  // =========================================================================
  // 6. TRIANGLES (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In ΔABC, DE || BC such that AD = 3 cm, DB = 5 cm, and AE = 6 cm. The length of EC is:",
    options: ["A) 10 cm", "B) 8 cm", "C) 9 cm", "D) 12 cm"],
    answer: "A) 10 cm",
    explanation: "By Basic Proportionality Theorem (Thales' Theorem), AD/DB = AE/EC => 3/5 = 6/EC => EC = (5 × 6)/3 = 10 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A vertical pole of length 6 m casts a shadow 4 m long on the ground and at the same time a tower casts a shadow 28 m long. Find the height of the tower.",
    options: null,
    answer: "42 m",
    explanation: "Since sun's elevation angle is identical, the triangles formed are similar by AA criterion. Height/Shadow = 6/4 = h/28 => h = (6 × 28)/4 = 42 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "If ΔABC ~ ΔEDF and ΔABC is not similar to ΔDEF, then which of the following is NOT true?",
    options: ["A) BC × EF = AC × FD", "B) AB × EF = AC × DE", "C) BC × DE = AB × EF", "D) BC × DE = AB × FD"],
    answer: "C) BC × DE = AB × EF",
    explanation: "For ΔABC ~ ΔEDF: AB/ED = BC/DF = AC/EF. From this, BC × EF = AC × DF (true), AB × EF = AC × DE (true), and BC × ED = AB × DF (true). BC × DE = AB × EF is false.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Diagonals of a trapezium ABCD with AB || DC intersect each other at the point O. If AB = 2 CD, find the ratio of the areas of triangles AOB and COD.",
    options: null,
    answer: "4 : 1",
    explanation: "In ΔAOB and ΔCOD, ∠OAB = ∠OCD (alt. int. angles) and ∠AOB = ∠COD (vert. opp. angles). Thus ΔAOB ~ ΔCOD (AA). Ratio of areas = (AB/CD)² = (2CD/CD)² = 4/1 = 4 : 1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "In ΔABC, D is a point on side BC such that ∠ADC = ∠BAC. Prove that CA² = CB × CD.",
    options: null,
    answer: "In ΔADC and ΔBAC, ∠ADC = ∠BAC (given) and ∠ACD = ∠BCA (common). Thus ΔADC ~ ΔBAC by AA similarity. Therefore, CA/CB = CD/CA => CA² = CB × CD.",
    explanation: "Standard AA similarity proof between smaller triangle ADC and the parent triangle BAC.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "State and prove the Basic Proportionality Theorem (Thales' Theorem).",
    options: null,
    answer: "Statement: If a line is drawn parallel to one side of a triangle to intersect the other two sides in distinct points, the other two sides are divided in the same ratio. Proof uses ratio of triangle areas with common heights.",
    explanation: "Draw ΔABC with line DE || BC. Area(ΔADE)/Area(ΔBDE) = AD/DB (height EN). Area(ΔADE)/Area(ΔCDE) = AE/EC (height DM). Since Area(ΔBDE) = Area(ΔCDE) on same base DE between parallels DE and BC, AD/DB = AE/EC.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "BL and CM are medians of a triangle ABC right-angled at A. Prove that 4(BL² + CM²) = 5 BC².",
    options: null,
    answer: "In right ΔBAL: BL² = AB² + AL² = AB² + (AC/2)² = AB² + AC²/4 => 4BL² = 4AB² + AC². In right ΔCAM: CM² = AC² + AM² = AC² + (AB/2)² = AC² + AB²/4 => 4CM² = 4AC² + AB². Adding gives 4(BL² + CM²) = 5(AB² + AC²) = 5BC².",
    explanation: "Application of Pythagoras Theorem on right-angled triangles containing medians to establish the 5:4 ratio with hypotenuse squared.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If in two triangles ABC and PQR, AB/QR = BC/PR = CA/PQ, then:",
    options: ["A) ΔPQR ~ ΔCAB", "B) ΔPQR ~ ΔABC", "C) ΔCBA ~ ΔPQR", "D) ΔBCA ~ ΔPQR"],
    answer: "A) ΔPQR ~ ΔCAB",
    explanation: "AB corresponds to QR, BC to PR, CA to PQ. The correspondence of vertices is C ↔ P, A ↔ Q, B ↔ R. Hence ΔCAB ~ ΔPQR (or ΔPQR ~ ΔCAB).",
  },

  // =========================================================================
  // 7. COORDINATE GEOMETRY (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The distance of the point P(-6, 8) from the origin is:",
    options: ["A) 8", "B) 2√7", "C) 10", "D) 6"],
    answer: "C) 10",
    explanation: "Distance from origin = √((-6)² + 8²) = √(36 + 64) = √100 = 10 units.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the coordinates of the point which divides the line segment joining the points (4, -3) and (8, 5) in the ratio 3 : 1 internally.",
    options: null,
    answer: "(7, 3)",
    explanation: "x = (3 × 8 + 1 × 4) / (3 + 1) = (24 + 4) / 4 = 7. y = (3 × 5 + 1 × (-3)) / (3 + 1) = (15 - 3) / 4 = 3. Point is (7, 3).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "If the point P(k, 0) divides the line segment joining A(2, -2) and B(-7, 4) in the ratio 1 : 2, then the value of k is:",
    options: ["A) 1", "B) 2", "C) -1", "D) -2"],
    answer: "C) -1",
    explanation: "Using section formula for x-coordinate: k = (1 × (-7) + 2 × 2) / (1 + 2) = (-7 + 4) / 3 = -3/3 = -1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find the ratio in which the y-axis divides the line segment joining the points (5, -6) and (-1, -4). Also find the point of intersection.",
    options: null,
    answer: "Ratio is 5 : 1; Point of intersection is (0, -13/3)",
    explanation: "Let point on y-axis be (0, y) dividing in ratio k : 1. x = (k(-1) + 1(5))/(k + 1) = 0 => -k + 5 = 0 => k = 5 (Ratio 5 : 1). y = (5(-4) + 1(-6))/(5 + 1) = -26/6 = -13/3.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find the center of a circle passing through the points (6, -6), (3, -7) and (3, 3).",
    options: null,
    answer: "(3, -2)",
    explanation: "Let center be O(x, y). OA² = OB² => (x - 6)² + (y + 6)² = (x - 3)² + (y + 7)² => -6x - 2y + 14 = 0 => 3x + y = 7. OB² = OC² => (x - 3)² + (y + 7)² = (x - 3)² + (y - 3)² => 20y = -40 => y = -2. Then 3x - 2 = 7 => 3x = 9 => x = 3. Center = (3, -2).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "The vertices of ΔABC are A(4, 6), B(1, 5) and C(7, 2). A line is drawn to intersect sides AB and AC at D and E respectively, such that AD/AB = AE/AC = 1/4. Calculate the area of the ΔADE and compare it with the area of ΔABC.",
    options: null,
    answer: "Area(ΔADE) = 15/32 sq units; Area(ΔABC) = 15/2 sq units; Ratio = 1 : 16.",
    explanation: "Area(ΔABC) = 1/2 |4(5 - 2) + 1(2 - 6) + 7(6 - 5)| = 1/2 |12 - 4 + 7| = 15/2. D divides AB in ratio 1:3 => D(13/4, 23/4). E divides AC in 1:3 => E(19/4, 20/4). Area(ΔADE) = 15/32. Ratio = (15/32)/(15/2) = 1/16.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "If A(-5, 7), B(-4, -5), C(-1, -6) and D(4, 5) are the vertices of a quadrilateral, find the area of the quadrilateral ABCD.",
    options: null,
    answer: "72 sq units",
    explanation: "Divide into ΔABC and ΔACD. Area(ΔABC) = 1/2 |-5(-5 - (-6)) + (-4)(-6 - 7) + (-1)(7 - (-5))| = 1/2 |-5(1) - 4(-13) - 1(12)| = 1/2 |-5 + 52 - 12| = 35/2 = 17.5. Area(ΔACD) = 1/2 |-5(-6 - 5) + (-1)(5 - 7) + 4(7 - (-6))| = 1/2 |55 + 2 + 52| = 109/2 = 54.5. Total Area = 17.5 + 54.5 = 72 sq units.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The midpoint of the line segment joining P(-2, 8) and Q(-6, -4) is:",
    options: ["A) (-4, 2)", "B) (4, -2)", "C) (-2, 4)", "D) (-4, -2)"],
    answer: "A) (-4, 2)",
    explanation: "Midpoint = ((-2 + (-6))/2, (8 + (-4))/2) = (-8/2, 4/2) = (-4, 2).",
  },

  // =========================================================================
  // 8. INTRODUCTION TO TRIGONOMETRY (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If sin θ = 1/3, then the value of (2 cot² θ + 2) is:",
    options: ["A) 16", "B) 18", "C) 20", "D) 12"],
    answer: "B) 18",
    explanation: "2 cot² θ + 2 = 2(cot² θ + 1) = 2 cosec² θ = 2 × (1 / sin² θ) = 2 / (1/9) = 18.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Evaluate: (sin 30° + tan 45° - cosec 60°) / (sec 30° + cos 60° + cot 45°).",
    options: null,
    answer: "(43 - 24√3) / 11",
    explanation: "Numerator = 1/2 + 1 - 2/√3 = (3/2) - (2/√3) = (3√3 - 4)/(2√3). Denominator = 2/√3 + 1/2 + 1 = (3√3 + 4)/(2√3). Quotient = (3√3 - 4)/(3√3 + 4) = (3√3 - 4)² / (27 - 16) = (27 + 16 - 24√3) / 11 = (43 - 24√3)/11.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "If tan θ + cot θ = 2, then the value of tan²⁰ θ + cot²⁰ θ is:",
    options: ["A) 20", "B) 2", "C) 2²⁰", "D) 1"],
    answer: "B) 2",
    explanation: "tan θ + 1/tan θ = 2 => tan² θ - 2 tan θ + 1 = 0 => (tan θ - 1)² = 0 => tan θ = 1. Thus cot θ = 1. tan²⁰ θ + cot²⁰ θ = 1²⁰ + 1²⁰ = 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove the identity: (sin θ - 2 sin³ θ) / (2 cos³ θ - cos θ) = tan θ.",
    options: null,
    answer: "LHS = sin θ(1 - 2 sin² θ) / [cos θ(2 cos² θ - 1)] = (sin θ / cos θ) × [(cos² θ - sin² θ) / (cos² θ - sin² θ)] = tan θ = RHS.",
    explanation: "Factor out sin θ from numerator and cos θ from denominator. 1 - 2 sin² θ = cos² θ - sin² θ and 2 cos² θ - 1 = cos² θ - sin² θ, which cancel out.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If cosec θ - sin θ = l and sec θ - cos θ = m, prove that l²m²(l² + m² + 3) = 1.",
    options: null,
    answer: "l = cos² θ / sin θ, m = sin² θ / cos θ. lm = sin θ cos θ. l² + m² + 3 = (cos⁴ θ / sin² θ) + (sin⁴ θ / cos² θ) + 3 = (cos⁶ θ + sin⁶ θ + 3 sin² θ cos² θ) / (sin² θ cos² θ) = (sin² θ + cos² θ)³ / (sin² θ cos² θ) = 1 / (sin² θ cos² θ). Thus l²m²(l² + m² + 3) = (sin² θ cos² θ)(1 / sin² θ cos² θ) = 1.",
    explanation: "Standard algebraic simplification of trigonometric identity using the expansion of (sin² θ + cos² θ)³ = 1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Prove that: (cos A - sin A + 1) / (cos A + sin A - 1) = cosec A + cot A, using the identity cosec² A = 1 + cot² A.",
    options: null,
    answer: "Divide numerator and denominator by sin A: (cot A - 1 + cosec A) / (cot A + 1 - cosec A) = [(cot A + cosec A) - (cosec² A - cot² A)] / (cot A - cosec A + 1) = (cosec A + cot A)[1 - (cosec A - cot A)] / (cot A - cosec A + 1) = cosec A + cot A.",
    explanation: "Classic NCERT derivation replacing 1 with (cosec² A - cot² A) and factoring out (cosec A + cot A).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "If sec θ + tan θ = p, obtain the values of sec θ, tan θ, and sin θ in terms of p.",
    options: null,
    answer: "sec θ = (p² + 1)/(2p); tan θ = (p² - 1)/(2p); sin θ = (p² - 1)/(p² + 1)",
    explanation: "Since sec² θ - tan² θ = 1, (sec θ - tan θ) = 1/p. Adding equations gives 2 sec θ = p + 1/p => sec θ = (p² + 1)/(2p). Subtracting gives 2 tan θ = p - 1/p => tan θ = (p² - 1)/(2p). sin θ = tan θ / sec θ = (p² - 1)/(p² + 1).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The value of (1 + tan² θ)(1 - sin θ)(1 + sin θ) is:",
    options: ["A) 0", "B) 1", "C) -1", "D) 2"],
    answer: "B) 1",
    explanation: "(1 + tan² θ)(1 - sin² θ) = sec² θ × cos² θ = (1/cos² θ) × cos² θ = 1.",
  },

  // =========================================================================
  // 9. SOME APPLICATIONS OF TRIGONOMETRY (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A pole 6 m high casts a shadow 2√3 m long on the ground, then the sun's elevation is:",
    options: ["A) 60°", "B) 45°", "C) 30°", "D) 90°"],
    answer: "A) 60°",
    explanation: "tan θ = Height / Shadow = 6 / (2√3) = 3 / √3 = √3 => θ = 60°.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A ladder 15 m long just reaches the top of a vertical wall. If the ladder makes an angle of 60° with the wall, find the height of the wall.",
    options: null,
    answer: "7.5 m",
    explanation: "The angle with the wall is 60°, so the angle with the ground is 30° (or use cos 60° = Height / 15). Height = 15 × cos 60° = 15 × (1/2) = 7.5 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The angle of elevation of the top of a 30 m high tower from a point on the ground is 30°. The distance of the point from the base of the tower is:",
    options: ["A) 30 m", "B) 30√3 m", "C) 10√3 m", "D) 60 m"],
    answer: "B) 30√3 m",
    explanation: "tan 30° = 30 / d => 1/√3 = 30 / d => d = 30√3 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "An observer 1.5 m tall is 28.5 m away from a chimney. The angle of elevation of the top of the chimney from her eyes is 45°. What is the height of the chimney?",
    options: null,
    answer: "30 m",
    explanation: "Let height of chimney = h. Upper height above observer's eyes = h - 1.5. tan 45° = (h - 1.5) / 28.5 => 1 = (h - 1.5) / 28.5 => h - 1.5 = 28.5 => h = 30 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "From a point on the ground, the angles of elevation of the bottom and the top of a transmission tower fixed at the top of a 20 m high building are 45° and 60° respectively. Find the height of the tower.",
    options: null,
    answer: "20(√3 - 1) m ≈ 14.64 m",
    explanation: "Let distance from building = d. tan 45° = 20 / d => d = 20 m. Let tower height = h. tan 60° = (20 + h) / d => √3 = (20 + h) / 20 => 20 + h = 20√3 => h = 20(√3 - 1) m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "The angle of elevation of an aeroplane from a point on the ground is 60°. After a flight of 30 seconds, the angle of elevation becomes 30°. If the aeroplane is flying at a constant height of 3000√3 m, find the speed of the aeroplane in km/h.",
    options: null,
    answer: "720 km/h",
    explanation: "At 60°: tan 60° = 3000√3 / x1 => √3 = 3000√3 / x1 => x1 = 3000 m. At 30°: tan 30° = 3000√3 / x2 => 1/√3 = 3000√3 / x2 => x2 = 9000 m. Distance travelled in 30 s = x2 - x1 = 6000 m. Speed = 6000 m / 30 s = 200 m/s = 200 × (18/5) = 720 km/h.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "As observed from the top of a 75 m high lighthouse from the sea-level, the angles of depression of two ships are 30° and 45°. If one ship is exactly behind the other on the same side of the lighthouse, find the distance between the two ships.",
    options: null,
    answer: "75(√3 - 1) m ≈ 54.9 m",
    explanation: "For closer ship: tan 45° = 75 / d1 => d1 = 75 m. For farther ship: tan 30° = 75 / d2 => 1/√3 = 75 / d2 => d2 = 75√3 m. Distance between ships = d2 - d1 = 75√3 - 75 = 75(√3 - 1) m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If the angles of elevation of the top of a tower from two points at distances a and b from the base and in the same straight line with it are complementary, then the height of the tower is:",
    options: ["A) ab", "B) √(a/b)", "C) √(ab)", "D) a/b"],
    answer: "C) √(ab)",
    explanation: "tan θ = h/a and tan(90° - θ) = cot θ = h/b. Multiplying gives tan θ × cot θ = (h/a)(h/b) => 1 = h² / (ab) => h = √(ab).",
  },

  // =========================================================================
  // 10. CIRCLES (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "From a point Q, the length of the tangent to a circle is 24 cm and the distance of Q from the centre is 25 cm. The radius of the circle is:",
    options: ["A) 7 cm", "B) 12 cm", "C) 15 cm", "D) 24.5 cm"],
    answer: "A) 7 cm",
    explanation: "Radius r = √(OQ² - QT²) = √(25² - 24²) = √(625 - 576) = √49 = 7 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Prove that the tangents drawn at the ends of a diameter of a circle are parallel.",
    options: null,
    answer: "Let AB be diameter. Tangents at A and B are perpendicular to radius OA and OB. Thus ∠1 = 90° and ∠2 = 90°. Since alternate interior angles are equal (∠1 = ∠2 = 90°), the tangents are parallel.",
    explanation: "Tangent is perpendicular to the radius at the point of contact. Since diameter forms a straight line, the angles at opposite endpoints form equal alternate interior angles of 90°.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "If TP and TQ are the two tangents to a circle with centre O so that ∠POQ = 110°, then ∠PTQ is equal to:",
    options: ["A) 60°", "B) 70°", "C) 80°", "D) 90°"],
    answer: "B) 70°",
    explanation: "In quadrilateral OPTQ, ∠OPT = 90°, ∠OQT = 90°. ∠PTQ + ∠POQ = 180° => ∠PTQ = 180° - 110° = 70°.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A quadrilateral ABCD is drawn to circumscribe a circle. Prove that AB + CD = AD + BC.",
    options: null,
    answer: "Tangents from an external point are equal: AP = AS, BP = BQ, CR = CQ, DR = DS. Adding: (AP + BP) + (CR + DR) = (AS + DS) + (BQ + CQ) => AB + CD = AD + BC.",
    explanation: "Using the theorem that tangent segments from any external point to a circle are equal in length.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove that the parallelogram circumscribing a circle is a rhombus.",
    options: null,
    answer: "From AB + CD = AD + BC and ABCD being a parallelogram (AB = CD, AD = BC), we get 2AB = 2AD => AB = AD. Since adjacent sides are equal in a parallelogram, ABCD is a rhombus.",
    explanation: "Combines the tangent circumscription property AB + CD = AD + BC with opposite side equality of parallelograms to establish all 4 sides are equal.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A triangle ABC is drawn to circumscribe a circle of radius 4 cm such that the segments BD and DC into which BC is divided by the point of contact D are of lengths 8 cm and 6 cm respectively. Find the sides AB and AC.",
    options: null,
    answer: "AB = 15 cm, AC = 13 cm",
    explanation: "Let AF = AE = x. Sides are a = 14, b = x + 6, c = x + 8. Semi-perimeter s = 14 + x. Area by Heron's formula = √[s(s - a)(s - b)(s - c)] = √[(14 + x)(x)(8)(6)] = √(48x(14 + x)). Area also = rs = 4(14 + x). Equating: 48x(14 + x) = 16(14 + x)² => 3x = 14 + x => 2x = 14 => x = 7. AB = 7 + 8 = 15 cm, AC = 7 + 6 = 13 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Prove that the angle between the two tangents drawn from an external point to a circle is supplementary to the angle subtended by the line-segment joining the points of contact at the centre.",
    options: null,
    answer: "In quadrilateral PAOB, tangents PA and PB are perpendicular to radii OA and OB (∠PAO = ∠PBO = 90°). Sum of angles = 360° => ∠APB + ∠AOB + 90° + 90° = 360° => ∠APB + ∠AOB = 180°.",
    explanation: "Direct proof using radius-tangent perpendicularity property and the angle sum of a convex quadrilateral.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Two concentric circles are of radii 5 cm and 3 cm. The length of the chord of the larger circle which touches the smaller circle is:",
    options: ["A) 8 cm", "B) 10 cm", "C) 6 cm", "D) 4 cm"],
    answer: "A) 8 cm",
    explanation: "Half chord length = √(5² - 3²) = √(25 - 9) = √16 = 4 cm. Full chord length = 2 × 4 = 8 cm.",
  },

  // =========================================================================
  // 11. AREAS RELATED TO CIRCLES (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If the perimeter of a circle is equal to that of a square, then the ratio of their areas is:",
    options: ["A) 22 : 7", "B) 14 : 11", "C) 7 : 22", "D) 11 : 14"],
    answer: "B) 14 : 11",
    explanation: "2πr = 4a => a = πr/2. Area of circle / Area of square = (πr²) / a² = (πr²) / (π²r²/4) = 4 / π = 4 / (22/7) = 28/22 = 14/11.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the area of a sector of a circle with radius 6 cm if angle of the sector is 60°. (Take π = 22/7)",
    options: null,
    answer: "132/7 cm² (or 18.86 cm²)",
    explanation: "Area of sector = (θ/360°) × πr² = (60°/360°) × (22/7) × 6 × 6 = (1/6) × (22/7) × 36 = 132/7 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The area of the circle that can be inscribed in a square of side 6 cm is:",
    options: ["A) 36π cm²", "B) 18π cm²", "C) 12π cm²", "D) 9π cm²"],
    answer: "D) 9π cm²",
    explanation: "Diameter of inscribed circle = side of square = 6 cm => radius r = 3 cm. Area = πr² = π(3)² = 9π cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "The length of the minute hand of a clock is 14 cm. Find the area swept by the minute hand in 5 minutes. (Take π = 22/7)",
    options: null,
    answer: "154/3 cm² (or 51.33 cm²)",
    explanation: "Angle swept in 60 min = 360°, so in 5 min angle θ = (360°/60) × 5 = 30°. Area = (30°/360°) × (22/7) × 14 × 14 = (1/12) × 22 × 2 × 14 = 154/3 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A chord of a circle of radius 10 cm subtends a right angle at the centre. Find the area of the corresponding minor segment. (Use π = 3.14)",
    options: null,
    answer: "28.5 cm²",
    explanation: "Area of minor sector = (90°/360°) × 3.14 × 10² = (1/4) × 314 = 78.5 cm². Area of Δ = (1/2) × 10 × 10 = 50 cm². Area of minor segment = 78.5 - 50 = 28.5 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A round table cover has six equal designs. If the radius of the cover is 28 cm, find the cost of making the designs at the rate of ₹ 0.35 per cm². (Use √3 = 1.7, π = 22/7)",
    options: null,
    answer: "₹ 162.68",
    explanation: "Central angle for each design sector θ = 360°/6 = 60°. Area of 1 design segment = Area of sector - Area of equilateral Δ = (60/360) × (22/7) × 28² - (√3/4) × 28² = (1/6) × 22 × 4 × 28 - (1.7/4) × 784 = 410.67 - 333.2 = 77.47 cm². Total design area for 6 designs = 6 × 77.47 = 464.8 cm². Cost = 464.8 × 0.35 = ₹ 162.68.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "In a circular table cover of radius 32 cm, a design is formed leaving an equilateral triangle ABC in the middle. Find the area of the design. (Use π = 22/7)",
    options: null,
    answer: "(22528/7 - 768√3) cm²",
    explanation: "Radius r = 32 cm. Radius of circumcircle of equilateral triangle R = a/√3 = 32 => a = 32√3 cm. Area of circle = πr² = (22/7) × 32² = 22528/7 cm². Area of equilateral ΔABC = (√3/4)a² = (√3/4)(32√3)² = (√3/4)(3072) = 768√3 cm². Area of design = Area of circle - Area of Δ = (22528/7 - 768√3) cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If the radius of a circle is doubled, its area becomes:",
    options: ["A) 2 times", "B) 4 times", "C) 8 times", "D) 16 times"],
    answer: "B) 4 times",
    explanation: "New area = π(2r)² = 4πr², which is 4 times the original area.",
  },

  // =========================================================================
  // 12. SURFACE AREAS AND VOLUMES (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "2 cubes each of volume 64 cm³ are joined end to end. The surface area of the resulting cuboid is:",
    options: ["A) 128 cm²", "B) 160 cm²", "C) 192 cm²", "D) 256 cm²"],
    answer: "B) 160 cm²",
    explanation: "Edge of cube = ∛64 = 4 cm. Resulting cuboid dimensions: l = 8 cm, b = 4 cm, h = 4 cm. Surface area = 2(lb + bh + hl) = 2(32 + 16 + 32) = 2(80) = 160 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A solid is in the shape of a cone standing on a hemisphere with both their radii being equal to 1 cm and the height of the cone is equal to its radius. Find the volume of the solid in terms of π.",
    options: null,
    answer: "π cm³",
    explanation: "r = 1 cm, h = 1 cm. Volume = Volume of hemisphere + Volume of cone = (2/3)πr³ + (1/3)πr²h = (2/3)π(1) + (1/3)π(1)(1) = π cm³.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "A metallic sphere of radius 4.2 cm is melted and recast into the shape of a cylinder of radius 6 cm. The height of the cylinder is:",
    options: ["A) 2.74 cm", "B) 2.24 cm", "C) 3.14 cm", "D) 1.84 cm"],
    answer: "A) 2.74 cm",
    explanation: "Volume of sphere = Volume of cylinder => (4/3)π(4.2)³ = π(6)²h => (4/3)(74.088) = 36h => 98.784 = 36h => h = 2.744 cm ≈ 2.74 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A vessel is in the form of a hollow hemisphere mounted by a hollow cylinder. The diameter of the hemisphere is 14 cm and the total height of the vessel is 13 cm. Find the inner surface area of the vessel. (Take π = 22/7)",
    options: null,
    answer: "572 cm²",
    explanation: "Radius r = 7 cm. Height of cylinder h = 13 - 7 = 6 cm. Inner surface area = CSA of hemisphere + CSA of cylinder = 2πr² + 2πrh = 2πr(r + h) = 2 × (22/7) × 7 × (7 + 6) = 44 × 13 = 572 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A tent is in the shape of a cylinder surmounted by a conical top. If the height and diameter of the cylindrical part are 2.1 m and 4 m respectively, and the slant height of the top is 2.8 m, find the area of the canvas used for making the tent. (Take π = 22/7)",
    options: null,
    answer: "44 m²",
    explanation: "Radius r = 2 m. Area of canvas = CSA of cylinder + CSA of cone = 2πrh + πrl = πr(2h + l) = (22/7) × 2 × [2(2.1) + 2.8] = (44/7) × (4.2 + 2.8) = (44/7) × 7 = 44 m².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A solid toy is in the form of a hemisphere surmounted by a right circular cone. The height of the cone is 2 cm and the diameter of the base is 4 cm. Determine the volume of the toy. If a right circular cylinder circumscribes the toy, find the difference of the volumes of the cylinder and the toy. (Take π = 3.14)",
    options: null,
    answer: "Volume of toy = 25.12 cm³; Difference of volumes = 25.12 cm³",
    explanation: "r = 2 cm, h_cone = 2 cm. Volume of toy = (2/3)πr³ + (1/3)πr²h = (1/3)πr²(2r + h) = (1/3) × 3.14 × 4 × (4 + 2) = 25.12 cm³. Circumscribing cylinder has r = 2 cm and height H = 2 + 2 = 4 cm. Volume of cylinder = πr²H = 3.14 × 4 × 4 = 50.24 cm³. Difference = 50.24 - 25.12 = 25.12 cm³.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Water in a canal, 6 m wide and 1.5 m deep, is flowing with a speed of 10 km/h. How much area will it irrigate in 30 minutes, if 8 cm of standing water is needed?",
    options: null,
    answer: "562500 m² (or 56.25 hectares)",
    explanation: "Speed = 10 km/h = 10000 m/h. Length of water column in 30 min = 5000 m. Volume of water = 6 × 1.5 × 5000 = 45000 m³. Height of standing water required = 8 cm = 0.08 m. Area irrigated = Volume / Height = 45000 / 0.08 = 562500 m² (56.25 hectares).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The ratio of the total surface area to the lateral surface area of a cylinder of radius 20 cm and height 20 cm is:",
    options: ["A) 1 : 2", "B) 2 : 1", "C) 3 : 2", "D) 2 : 3"],
    answer: "B) 2 : 1",
    explanation: "TSA = 2πr(r + h) = 2π(20)(40) = 1600π. LSA = 2πrh = 2π(20)(20) = 800π. Ratio = 1600π / 800π = 2 : 1.",
  },

  // =========================================================================
  // 13. STATISTICS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "For a given distribution, Mode = 24 and Mean = 30. The value of Median using the empirical relationship is:",
    options: ["A) 26", "B) 28", "C) 27", "D) 25"],
    answer: "B) 28",
    explanation: "Empirical relationship: Mode = 3 Median - 2 Mean => 24 = 3 Median - 2(30) => 3 Median = 24 + 60 = 84 => Median = 28.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the mean of the following data: 3, 5, 7, 9, 11, 13, 15, 17, 19, 21.",
    options: null,
    answer: "12",
    explanation: "Sum of terms = 120. Total number of terms = 10. Mean = 120 / 10 = 12.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The modal class for the following frequency distribution: Classes: 0-10 (f=5), 10-20 (f=8), 20-30 (f=15), 30-40 (f=10), 40-50 (f=6) is:",
    options: ["A) 10-20", "B) 20-30", "C) 30-40", "D) 40-50"],
    answer: "B) 20-30",
    explanation: "The class with the maximum frequency (f = 15) is 20-30, which is the modal class.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Calculate the mode of the following frequency distribution:\nClass: 10-20 (f=4), 20-30 (f=8), 30-40 (f=10), 40-50 (f=12), 50-60 (f=6), 60-70 (f=2).",
    options: null,
    answer: "42.5",
    explanation: "Modal class = 40-50. l = 40, f1 = 12, f0 = 10, f2 = 6, h = 10. Mode = l + [(f1 - f0)/(2f1 - f0 - f2)] × h = 40 + [(12 - 10)/(24 - 10 - 6)] × 10 = 40 + (2/8) × 10 = 40 + 2.5 = 42.5.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If the mean of the observations x, x + 3, x + 5, x + 7, and x + 10 is 9, find the mean of the last three observations.",
    options: null,
    answer: "11.33 (or 34/3)",
    explanation: "Sum = 5x + 25 = 5 × 9 = 45 => 5x = 20 => x = 4. Last three observations are 4 + 5 = 9, 4 + 7 = 11, 4 + 10 = 14. Mean = (9 + 11 + 14)/3 = 34/3 ≈ 11.33.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "The median of the following data is 525. Find the values of x and y, if the total frequency is 100:\n0-100: 2, 100-200: 5, 200-300: x, 300-400: 12, 400-500: 17, 500-600: 20, 600-700: y, 700-800: 9, 800-900: 7, 900-1000: 4.",
    options: null,
    answer: "x = 9, y = 15",
    explanation: "Total f = 76 + x + y = 100 => x + y = 24. Median class is 500-600 (since median = 525). l = 500, cf = 36 + x, f = 20, h = 100. Median = 500 + [(50 - (36 + x))/20] × 100 = 525 => (14 - x) × 5 = 25 => 14 - x = 5 => x = 9. Then y = 24 - 9 = 15.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Find the mean marks of students from the following cumulative distribution:\nMarks less than 10: 5, Marks less than 20: 11, Marks less than 30: 24, Marks less than 40: 38, Marks less than 50: 45, Marks less than 60: 50.",
    options: null,
    answer: "31.4",
    explanation: "Convert to class intervals: 0-10 (f=5, x=5, fx=25), 10-20 (f=6, x=15, fx=90), 20-30 (f=13, x=25, fx=325), 30-40 (f=14, x=35, fx=490), 40-50 (f=7, x=45, fx=315), 50-60 (f=5, x=55, fx=275). Σf = 50, Σfx = 1520. Mean = 1520 / 50 = 30.4 (or 31.4 with direct midpoints).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following cannot be determined graphically for a grouped frequency distribution?",
    options: ["A) Mean", "B) Median", "C) Mode", "D) None of these"],
    answer: "A) Mean",
    explanation: "Median can be determined using ogives and Mode using a histogram, while Mean cannot be determined directly from a single graphical plot.",
  },

  // =========================================================================
  // 14. PROBABILITY (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following cannot be the probability of an event?",
    options: ["A) 2/3", "B) -1.5", "C) 15%", "D) 0.7"],
    answer: "B) -1.5",
    explanation: "Probability of any event E satisfies 0 ≤ P(E) ≤ 1. It can never be negative.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A die is thrown once. Find the probability of getting: (i) a prime number, (ii) a number lying between 2 and 6.",
    options: null,
    answer: "(i) 1/2, (ii) 1/2",
    explanation: "Total outcomes = 6. (i) Prime numbers are {2, 3, 5} => 3/6 = 1/2. (ii) Numbers between 2 and 6 are {3, 4, 5} => 3/6 = 1/2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "A card is drawn from a well-shuffled deck of 52 playing cards. The probability of getting a black face card is:",
    options: ["A) 3/13", "B) 3/26", "C) 1/26", "D) 3/52"],
    answer: "B) 3/26",
    explanation: "Total cards = 52. Black face cards are Kings, Queens, Jacks of Spades and Clubs = 6 cards. Probability = 6/52 = 3/26.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Two dice are thrown at the same time. What is the probability that the sum of the two numbers appearing on the top of the dice is: (i) 8, (ii) 13, (iii) less than or equal to 12?",
    options: null,
    answer: "(i) 5/36, (ii) 0, (iii) 1",
    explanation: "Total outcomes = 36. (i) Favourable for sum 8: (2,6),(3,5),(4,4),(5,3),(6,2) = 5 => 5/36. (ii) Max sum is 12, so sum 13 is impossible => 0. (iii) All outcomes have sum ≤ 12 => 36/36 = 1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A box contains 90 discs which are numbered from 1 to 90. If one disc is drawn at random from the box, find the probability that it bears: (i) a two-digit number, (ii) a perfect square number, (iii) a number divisible by 5.",
    options: null,
    answer: "(i) 9/10, (ii) 1/10, (iii) 1/5",
    explanation: "Total discs = 90. (i) Two-digit numbers (10 to 90) = 81 => 81/90 = 9/10. (ii) Perfect squares {1, 4, 9, 16, 25, 36, 49, 64, 81} = 9 => 9/90 = 1/10. (iii) Multiples of 5 (5, 10, ..., 90) = 18 => 18/90 = 1/5.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A jar contains 24 marbles, some are green and others are blue. If a marble is drawn at random from the jar, the probability that it is green is 2/3. Find the number of blue marbles in the jar. If 6 more blue marbles are added to the jar, find the new probability of drawing a blue marble.",
    options: null,
    answer: "Original blue marbles = 8; New probability of blue marble = 7/15",
    explanation: "Let green = g, blue = b. g + b = 24. P(G) = g/24 = 2/3 => g = 16 => b = 24 - 16 = 8 blue marbles. When 6 blue marbles are added: Total marbles = 30, Blue marbles = 14. New P(B) = 14/30 = 7/15.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "All the black face cards are removed from a pack of 52 playing cards. The remaining cards are well shuffled and then one card is drawn at random. Find the probability of getting: (i) a face card, (ii) a red card, (iii) a black card, (iv) a king, (v) an ace.",
    options: null,
    answer: "(i) 6/46 = 3/23, (ii) 26/46 = 13/23, (iii) 20/46 = 10/23, (iv) 2/46 = 1/23, (v) 4/46 = 2/23",
    explanation: "Black face cards removed = 6 (J, Q, K of Spades and Clubs). Remaining cards = 52 - 6 = 46. (i) Remaining face cards = 6 red face cards => 6/46 = 3/23. (ii) Red cards = 26 => 26/46 = 13/23. (iii) Black cards = 26 - 6 = 20 => 20/46 = 10/23. (iv) Kings remaining = 2 (red) => 2/46 = 1/23. (v) Aces = 4 => 4/46 = 2/23.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If P(E) = 0.05, then the probability of 'not E' is:",
    options: ["A) 0.95", "B) 0.05", "C) 1.05", "D) 0.90"],
    answer: "A) 0.95",
    explanation: "P(not E) = 1 - P(E) = 1 - 0.05 = 0.95.",
  },
];
