import { QuestionInput } from "@/types/question";

export const MATH_QUESTIONS: QuestionInput[] = [
  // --- 1. REAL NUMBERS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If two positive integers a and b are written as a = x³y² and b = xy³, where x, y are prime numbers, then HCF(a, b) is:",
    options: ["A) xy", "B) xy²", "C) x³y³", "D) x²y²"],
    answer: "B) xy²",
    explanation: "HCF is the product of the smallest power of each common prime factor involved in the numbers. Smallest power of x is x¹ and of y is y². Hence HCF(a, b) = xy².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Explain why 7 × 11 × 13 + 13 is a composite number.",
    options: null,
    answer: "The given expression can be factored as 13 × (7 × 11 + 1) = 13 × 78 = 2 × 3 × 13².",
    explanation: "Since the given number has prime factors other than 1 and the number itself (factors 2, 3, and 13), it is a composite number by the Fundamental Theorem of Arithmetic.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The least number that is divisible by all the numbers from 1 to 10 (both inclusive) is:",
    options: ["A) 10", "B) 100", "C) 504", "D) 2520"],
    answer: "D) 2520",
    explanation: "LCM(1, 2, 3, 4, 5, 6, 7, 8, 9, 10) = 2³ × 3² × 5 × 7 = 8 × 9 × 5 × 7 = 2520.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove that 3 + 2√5 is an irrational number, given that √5 is irrational.",
    options: null,
    answer: "Let 3 + 2√5 = a/b (where a, b are co-prime integers, b ≠ 0). Then 2√5 = a/b - 3 = (a - 3b)/b => √5 = (a - 3b)/(2b). Since a and b are integers, (a - 3b)/(2b) is rational, meaning √5 is rational. This contradicts the fact that √5 is irrational. Hence 3 + 2√5 is irrational.",
    explanation: "Contradiction proof showing that assuming rationality yields √5 as a quotient of integers, violating its given irrationality.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "There is a circular path around a sports field. Sonia takes 18 minutes to drive one round of the field, while Ravi takes 12 minutes for the same. Suppose they both start at the same point and at the same time, and go in the same direction. After how many minutes will they meet again at the starting point? Also, determine the number of rounds completed by each.",
    options: null,
    answer: "They will meet after 36 minutes. Sonia will complete 2 rounds and Ravi will complete 3 rounds.",
    explanation: "They will meet again at the starting point at a time which is the LCM of 18 and 12. 18 = 2 × 3², 12 = 2² × 3. LCM(18, 12) = 2² × 3² = 36 minutes. Rounds by Sonia = 36 / 18 = 2; Rounds by Ravi = 36 / 12 = 3.",
  },

  // --- 2. POLYNOMIALS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If one zero of the quadratic polynomial x² + 3x + k is 2, then the value of k is:",
    options: ["A) 10", "B) -10", "C) -7", "D) -2"],
    answer: "B) -10",
    explanation: "Since 2 is a zero of p(x) = x² + 3x + k, p(2) = 0. So (2)² + 3(2) + k = 0 => 4 + 6 + k = 0 => k = -10.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find a quadratic polynomial whose sum and product of zeroes are -3 and 2 respectively.",
    options: null,
    answer: "k(x² + 3x + 2) where k is any non-zero constant.",
    explanation: "Standard quadratic polynomial formula: p(x) = k[x² - (Sum)x + (Product)] = k[x² - (-3)x + 2] = k(x² + 3x + 2).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find the zeroes of the quadratic polynomial 6x² - 3 - 7x and verify the relationship between the zeroes and the coefficients.",
    options: null,
    answer: "Zeroes are α = 3/2 and β = -1/3. Sum = 3/2 - 1/3 = 7/6 = -b/a. Product = (3/2)(-1/3) = -1/2 = -3/6 = c/a.",
    explanation: "Factorization of 6x² - 7x - 3 gives (2x - 3)(3x + 1) = 0. Roots are 3/2 and -1/3, satisfying sum = -b/a and product = c/a.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "If α and β are the zeroes of the polynomial f(x) = 2x² + 5x + k such that α² + β² + αβ = 21/4, then find the value of k.",
    options: ["A) 1", "B) 2", "C) 3", "D) 4"],
    answer: "B) 2",
    explanation: "α + β = -5/2, αβ = k/2. (α + β)² - αβ = (-5/2)² - k/2 = 25/4 - k/2 = 21/4 => k/2 = 4/4 = 1 => k = 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "If α and β are the zeroes of the quadratic polynomial p(x) = x² - 2x + 3, find a quadratic polynomial whose zeroes are (α + 2)/(α - 2) and (β + 2)/(β - 2).",
    options: null,
    answer: "The required quadratic polynomial is k(3x² - 2x + 11) where k is any non-zero real number.",
    explanation: "For p(x) = x² - 2x + 3: α + β = 2, αβ = 3. Sum of new zeroes S = 2/3 and product P = 11/3. Required polynomial: k[x² - (2/3)x + 11/3] = k(3x² - 2x + 11).",
  },

  // --- 3. PAIR OF LINEAR EQUATIONS IN TWO VARIABLES (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The pair of equations x + 2y + 5 = 0 and -3x - 6y + 1 = 0 has:",
    options: ["A) A unique solution", "B) Exactly two solutions", "C) Infinitely many solutions", "D) No solution"],
    answer: "D) No solution",
    explanation: "Here a1/a2 = 1/(-3) = -1/3, b1/b2 = 2/(-6) = -1/3, and c1/c2 = 5/1 = 5. Since a1/a2 = b1/b2 ≠ c1/c2, the lines are parallel and inconsistent (no solution).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the value of k for which the pair of linear equations kx + 3y = k - 3 and 12x + ky = k has infinitely many solutions.",
    options: null,
    answer: "k = 6",
    explanation: "For infinitely many solutions: a1/a2 = b1/b2 = c1/c2 => k/12 = 3/k = (k-3)/k. From k² = 36 => k = ±6. From 3k = k(k-3) => k = 6. Hence k = 6.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Solve the following pair of linear equations by elimination method: 3x + 4y = 10 and 2x - 2y = 2.",
    options: null,
    answer: "x = 2, y = 1",
    explanation: "Multiply equation 2 by 2: 4x - 4y = 4. Adding to equation 1: 7x = 14 => x = 2. Then 2(2) - 2y = 2 => 2y = 2 => y = 1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "A fraction becomes 9/11 if 2 is added to both numerator and denominator. If 3 is added to both numerator and denominator it becomes 5/6. Find the fraction.",
    options: null,
    answer: "The fraction is 7/9.",
    explanation: "Let fraction be x/y. (x+2)/(y+2) = 9/11 => 11x - 9y = -4. (x+3)/(y+3) = 5/6 => 6x - 5y = -3. Solving yields x = 7, y = 9.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A boat goes 30 km upstream and 44 km downstream in 10 hours. In 13 hours, it can go 40 km upstream and 55 km downstream. Determine the speed of the stream and that of the boat in still water.",
    options: null,
    answer: "Speed of boat in still water = 8 km/h; Speed of stream = 3 km/h.",
    explanation: "Let boat speed = x km/h and stream speed = y km/h. Let u = 1/(x-y) and v = 1/(x+y). 30u + 44v = 10 and 40u + 55v = 13. Solution gives u = 1/5, v = 1/11. Thus x - y = 5 and x + y = 11 => x = 8, y = 3.",
  },

  // --- 4. QUADRATIC EQUATIONS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following quadratic equations has no real roots?",
    options: ["A) 2x² - 3x + 1 = 0", "B) x² - 4x + 4 = 0", "C) x² + 2x + 5 = 0", "D) 2x² - 6x + 3 = 0"],
    answer: "C) x² + 2x + 5 = 0",
    explanation: "Discriminant D = b² - 4ac. For C: D = 2² - 4(1)(5) = 4 - 20 = -16 < 0. Therefore, no real roots.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the discriminant of the quadratic equation 2x² - 4x + 3 = 0, and hence state the nature of its roots.",
    options: null,
    answer: "Discriminant D = -8. The equation has no real roots.",
    explanation: "D = (-4)² - 4(2)(3) = 16 - 24 = -8. Since D < 0, roots are non-real (imaginary).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Solve the quadratic equation for x: 4x² - 4ax + (a² - b²) = 0 using the quadratic formula.",
    options: null,
    answer: "x = (a + b)/2 or x = (a - b)/2",
    explanation: "D = (-4a)² - 4(4)(a² - b²) = 16a² - 16a² + 16b² = 16b². x = [4a ± 4b] / 8 = (a ± b)/2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "Solve for x: 1/(x + 4) - 1/(x - 7) = 11/30 (where x ≠ -4, 7).",
    options: null,
    answer: "x = 1 or x = 2",
    explanation: "[(x - 7) - (x + 4)] / [(x + 4)(x - 7)] = 11/30 => -11 / (x² - 3x - 28) = 11/30 => x² - 3x - 28 = -30 => x² - 3x + 2 = 0 => (x - 1)(x - 2) = 0 => x = 1, 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 6,
    question: "A motor boat whose speed is 18 km/h in still water takes 1 hour more to go 24 km upstream than to return downstream to the same spot. Find the speed of the stream.",
    options: null,
    answer: "Speed of the stream = 6 km/h.",
    explanation: "Let speed of stream be w km/h. Speed upstream = 18 - w, downstream = 18 + w. Time difference: 24/(18 - w) - 24/(18 + w) = 1 => 24[(18 + w) - (18 - w)] / (324 - w²) = 1 => 24(2w) = 324 - w² => w² + 48w - 324 = 0 => (w + 54)(w - 6) = 0 => w = 6 km/h.",
  },

  // --- 5. ARITHMETIC PROGRESSIONS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The 11th term of the AP: -3, -1/2, 2, ... is:",
    options: ["A) 28", "B) 22", "C) -38", "D) -46 1/2"],
    answer: "B) 22",
    explanation: "a = -3, d = -1/2 - (-3) = 5/2. a11 = a + 10d = -3 + 10(5/2) = -3 + 25 = 22.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Which term of the AP: 21, 18, 15, ... is -81?",
    options: null,
    answer: "The 35th term is -81.",
    explanation: "a = 21, d = -3. an = a + (n-1)d => -81 = 21 + (n-1)(-3) => -102 = -3(n-1) => n - 1 = 34 => n = 35.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If the sum of the first 14 terms of an AP is 1050 and its first term is 10, find the 20th term.",
    options: null,
    answer: "The 20th term is 200.",
    explanation: "S14 = 7[2(10) + 13d] = 1050 => 20 + 13d = 150 => 13d = 130 => d = 10. a20 = 10 + 19(10) = 200.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "The sum of all two-digit odd positive integers is:",
    options: ["A) 2475", "B) 2530", "C) 4905", "D) 5049"],
    answer: "A) 2475",
    explanation: "Odd two-digit numbers: 11, 13, ..., 99. Here a = 11, d = 2, l = 99. 99 = 11 + (n-1)2 => n = 45. Sum = 45/2 (11 + 99) = 45/2 (110) = 45 × 55 = 2475.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "200 logs are stacked in the following manner: 20 logs in the bottom row, 19 in the next row, 18 in the row next to it and so on. In how many rows are the 200 logs placed and how many logs are in the top row?",
    options: null,
    answer: "There are 16 rows and 5 logs in the top row.",
    explanation: "a = 20, d = -1, Sn = 200. n/2 [2(20) + (n-1)(-1)] = 200 => n(41 - n) = 400 => n² - 41n + 400 = 0 => (n - 16)(n - 25) = 0. If n = 25, a25 = 20 + 24(-1) = -4 (impossible). So n = 16. Logs in top row = a16 = 20 + 15(-1) = 5.",
  },

  // --- 6. TRIANGLES (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In triangle ABC, D and E are points on sides AB and AC respectively such that DE || BC. If AD = 2 cm, DB = 3 cm, and AE = 1.6 cm, then EC is:",
    options: ["A) 2.4 cm", "B) 3.2 cm", "C) 4.8 cm", "D) 1.2 cm"],
    answer: "A) 2.4 cm",
    explanation: "By Thales theorem: AD/DB = AE/EC => 2/3 = 1.6/EC => EC = (1.6 × 3)/2 = 2.4 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "In ΔABC, DE || BC such that AD = x, DB = x - 2, AE = x + 2 and EC = x - 1. Find the value of x.",
    options: null,
    answer: "x = 4",
    explanation: "x/(x - 2) = (x + 2)/(x - 1) => x(x - 1) = (x - 2)(x + 2) => x² - x = x² - 4 => x = 4.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A vertical pole of length 6 m casts a shadow 4 m long on the ground and at the same time a tower casts a shadow 28 m long. Find the height of the tower.",
    options: null,
    answer: "Height of the tower = 42 m.",
    explanation: "By similarity (AA): 6/4 = h/28 => h = (6 × 28)/4 = 42 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "In an equilateral triangle ABC, D is a point on side BC such that BD = 1/3 BC. Prove that 9 AD² = 7 AB².",
    options: null,
    answer: "9 AD² = 7 AB²",
    explanation: "Draw AE ⊥ BC. In equilateral ΔABC, BE = BC/2 = a/2. Given BD = a/3. DE = BE - BD = a/2 - a/3 = a/6. AE² = AB² - BE² = a² - a²/4 = 3a²/4. In right ΔADE: AD² = AE² + DE² = 3a²/4 + (a/6)² = 3a²/4 + a²/36 = 28a²/36 = 7a²/9. Thus 9 AD² = 7 AB².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "State and prove the Basic Proportionality Theorem (Thales Theorem).",
    options: null,
    answer: "Statement: If a line is drawn parallel to one side of a triangle intersecting the other two sides in distinct points, the other two sides are divided in the same ratio.",
    explanation: "In ΔABC, line DE || BC. Area(ADE) = 1/2 × AD × EN. Area(BDE) = 1/2 × DB × EN. Ratio = AD/DB. Similarly Area(ADE)/Area(DEC) = AE/EC. Since Area(BDE) = Area(DEC) (same base DE between same parallels), AD/DB = AE/EC.",
  },

  // --- 7. COORDINATE GEOMETRY (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The distance of the point P(-6, 8) from the origin is:",
    options: ["A) 8", "B) 2√7", "C) 10", "D) 6"],
    answer: "C) 10",
    explanation: "Distance = √[(-6)² + 8²] = √(36 + 64) = √100 = 10 units.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the ratio in which the y-axis divides the line segment joining the points (5, -6) and (-1, -4).",
    options: null,
    answer: "The y-axis divides the segment in the ratio 5 : 1.",
    explanation: "Let ratio be k:1. On y-axis, x = 0. x = (k(-1) + 5)/(k + 1) = 0 => -k + 5 = 0 => k = 5. Ratio is 5:1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find a relation between x and y such that the point (x, y) is equidistant from the points (3, 6) and (-3, 4).",
    options: null,
    answer: "3x + y - 5 = 0",
    explanation: "(x - 3)² + (y - 6)² = (x + 3)² + (y - 4)² => -6x - 12y + 45 = 6x - 8y + 25 => 12x + 4y - 20 = 0 => 3x + y - 5 = 0.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "If the points A(6, 1), B(8, 2), C(9, 4) and D(p, 3) are the vertices of a parallelogram, taken in order, find the value of p.",
    options: null,
    answer: "p = 7",
    explanation: "Midpoint of diagonal AC = ((6+9)/2, (1+4)/2) = (15/2, 5/2). Midpoint of diagonal BD = ((8+p)/2, 5/2). Equating: (8+p)/2 = 15/2 => p = 7.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "Find the coordinates of the point which divides the join of (-1, 7) and (4, -3) in the ratio 2 : 3.",
    options: ["A) (1, 3)", "B) (2, 4)", "C) (3, 1)", "D) (-1, 2)"],
    answer: "A) (1, 3)",
    explanation: "x = (2(4) + 3(-1))/5 = 5/5 = 1. y = (2(-3) + 3(7))/5 = 15/5 = 3. Point is (1, 3).",
  },

  // --- 8. INTRODUCTION TO TRIGONOMETRY (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If sin θ = 1/2, then the value of (3 cos θ - 4 cos³ θ) is:",
    options: ["A) 0", "B) 1", "C) 1/2", "D) √3/2"],
    answer: "A) 0",
    explanation: "θ = 30°. cos 30° = √3/2. Expression = 3(√3/2) - 4(3√3/8) = 3√3/2 - 3√3/2 = 0.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "If tan(A + B) = √3 and tan(A - B) = 1/√3, 0° < A + B ≤ 90°, A > B, find A and B.",
    options: null,
    answer: "A = 45°, B = 15°",
    explanation: "A + B = 60° and A - B = 30°. Adding gives 2A = 90° => A = 45°. Subtracting gives 2B = 30° => B = 15°.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove the identity: (sin θ - 2 sin³ θ) / (2 cos³ θ - cos θ) = tan θ.",
    options: null,
    answer: "LHS = [sin θ(1 - 2 sin² θ)] / [cos θ(2 cos² θ - 1)] = [sin θ(cos² θ - sin² θ)] / [cos θ(cos² θ - sin² θ)] = tan θ = RHS.",
    explanation: "Factor out sin θ from numerator and cos θ from denominator and express 1 as sin² θ + cos² θ.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "If sec θ + tan θ = p, prove that sin θ = (p² - 1)/(p² + 1).",
    options: null,
    answer: "sec θ + tan θ = p, sec θ - tan θ = 1/p. Adding gives sec θ = (p² + 1)/(2p), subtracting gives tan θ = (p² - 1)/(2p). sin θ = tan θ / sec θ = (p² - 1)/(p² + 1).",
    explanation: "Using algebraic properties of sec² θ - tan² θ = 1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Prove that: (cos A - sin A + 1) / (cos A + sin A - 1) = cosec A + cot A, using the identity cosec² A = 1 + cot² A.",
    options: null,
    answer: "Divide numerator and denominator by sin A: (cot A - 1 + cosec A)/(cot A + 1 - cosec A) = [(cot A + cosec A) - (cosec² A - cot² A)] / (cot A - cosec A + 1) = [(cosec A + cot A)(1 - cosec A + cot A)] / (1 - cosec A + cot A) = cosec A + cot A.",
    explanation: "Dividing by sin A transforms the equation into cot A and cosec A, allowing substitution of 1 = cosec² A - cot² A.",
  },

  // --- 9. SOME APPLICATIONS OF TRIGONOMETRY (4 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The angle of elevation of the top of a tower from a point on the ground, 30 m away from the foot of the tower, is 30°. The height of the tower is:",
    options: ["A) 10√3 m", "B) 30√3 m", "C) 20√3 m", "D) 10 m"],
    answer: "A) 10√3 m",
    explanation: "tan 30° = h / 30 => 1/√3 = h / 30 => h = 30/√3 = 10√3 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A 1.5 m tall observer is 28.5 m away from a chimney. The angle of elevation of the top of the chimney from her eyes is 45°. What is the height of the chimney?",
    options: null,
    answer: "Height of chimney = 30 m.",
    explanation: "tan 45° = h'/28.5 => h' = 28.5 m. Total height = 28.5 + 1.5 = 30 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "If the shadow of a tower is √3 times its height, the sun's angle of elevation is:",
    options: ["A) 30°", "B) 45°", "C) 60°", "D) 90°"],
    answer: "A) 30°",
    explanation: "tan θ = h / (√3 h) = 1/√3 => θ = 30°.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "From the top of a 7 m high building, the angle of elevation of the top of a cable tower is 60° and the angle of depression of its foot is 45°. Determine the height of the tower (take √3 = 1.732).",
    options: null,
    answer: "Height of tower = 7(√3 + 1) = 19.124 m.",
    explanation: "In lower right triangle: tan 45° = 7/d => d = 7 m. In upper right triangle: tan 60° = h'/d => h' = 7√3 m. Total height = h' + 7 = 7(√3 + 1) = 7(2.732) = 19.124 m.",
  },

  // --- 10. CIRCLES (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "From a point Q, the length of the tangent to a circle is 24 cm and the distance of Q from the centre is 25 cm. The radius of the circle is:",
    options: ["A) 7 cm", "B) 12 cm", "C) 15 cm", "D) 24.5 cm"],
    answer: "A) 7 cm",
    explanation: "r = √(25² - 24²) = √(625 - 576) = √49 = 7 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "If tangents PA and PB from a point P to a circle with centre O are inclined to each other at an angle of 80°, then find ∠POA.",
    options: null,
    answer: "∠POA = 50°",
    explanation: "∠AOB = 180° - 80° = 100°. Line OP bisects ∠AOB => ∠POA = 100° / 2 = 50°.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove that the lengths of tangents drawn from an external point to a circle are equal.",
    options: null,
    answer: "In ΔOAP and ΔOBP: OA = OB (radii), OP = OP (common), ∠OAP = ∠OBP = 90°. By RHS criterion, ΔOAP ≅ ΔOBP => PA = PB.",
    explanation: "Standard circle theorem established via RHS triangle congruence.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Prove that the parallelogram circumscribing a circle is a rhombus.",
    options: null,
    answer: "In circumscribed ABCD: AB + CD = AD + BC. Since ABCD is a parallelogram, AB = CD and AD = BC => 2AB = 2AD => AB = AD. Since adjacent sides are equal, ABCD is a rhombus.",
    explanation: "Tangents from external points yield AP=AS, BP=BQ, CR=CQ, DR=DS, giving sum of opposite sides equal.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A triangle ABC is drawn to circumscribe a circle of radius 4 cm such that the segments BD and DC into which BC is divided by the point of contact D are of lengths 8 cm and 6 cm respectively. Find the sides AB and AC.",
    options: null,
    answer: "AB = 15 cm, AC = 13 cm.",
    explanation: "Let tangents from A be x. Semi-perimeter s = 14 + x. Area = √[48x(14+x)]. Also Area = 4(14+x). Equating gives 48x(14+x) = 16(14+x)² => 3x = 14 + x => x = 7 cm. AB = 8 + 7 = 15 cm, AC = 6 + 7 = 13 cm.",
  },

  // --- 11. AREAS RELATED TO CIRCLES (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If the perimeter and the area of a circle are numerically equal, then the radius of the circle is:",
    options: ["A) 2 units", "B) π units", "C) 4 units", "D) 7 units"],
    answer: "A) 2 units",
    explanation: "2πr = πr² => r = 2 units.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 2,
    question: "The length of the minute hand of a clock is 14 cm. Find the area swept by the minute hand in 5 minutes (use π = 22/7).",
    options: ["A) 154/3 cm²", "B) 154/6 cm²", "C) 308/3 cm²", "D) 77/3 cm²"],
    answer: "A) 154/3 cm²",
    explanation: "Angle θ = (360/60) × 5 = 30°. Area = (30/360) × (22/7) × 14 × 14 = 154/3 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "In a circle of radius 21 cm, an arc subtends an angle of 60° at the centre. Find: (i) the length of the arc, (ii) area of the sector formed by the arc.",
    options: null,
    answer: "(i) Length of arc = 22 cm, (ii) Area of sector = 231 cm².",
    explanation: "(i) Arc = (60/360) × 2 × (22/7) × 21 = 22 cm. (ii) Area = (60/360) × (22/7) × 21 × 21 = 231 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "A chord of a circle of radius 15 cm subtends an angle of 60° at the centre. Find the area of the minor segment of the circle (use π = 3.14 and √3 = 1.732).",
    options: null,
    answer: "Area of minor segment = 20.4375 cm².",
    explanation: "Sector area = (60/360) × 3.14 × 225 = 117.75 cm². Triangle area = (√3/4) × 225 = 97.3125 cm². Segment area = 117.75 - 97.3125 = 20.4375 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Find the area of the shaded region in a square ABCD of side 14 cm, where four quadrants of radius 3.5 cm are removed from the four corners and a circle of diameter 7 cm is removed from the centre (use π = 22/7).",
    options: null,
    answer: "Area of shaded region = 119 cm².",
    explanation: "Square area = 196 cm². Four quadrants = 38.5 cm². Central circle = 38.5 cm². Total removed = 77 cm². Shaded area = 196 - 77 = 119 cm².",
  },

  // --- 12. SURFACE AREAS AND VOLUMES (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "2 cubes each of volume 64 cm³ are joined end to end. The surface area of the resulting cuboid is:",
    options: ["A) 128 cm²", "B) 160 cm²", "C) 192 cm²", "D) 256 cm²"],
    answer: "B) 160 cm²",
    explanation: "Side of cube = 4 cm. Cuboid dimensions: 8 × 4 × 4. Surface area = 2(32 + 16 + 32) = 160 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "The curved surface area of a right circular cylinder of height 14 cm is 88 cm². Find the diameter of the base of the cylinder (use π = 22/7).",
    options: null,
    answer: "Diameter = 2 cm.",
    explanation: "2πrh = 88 => 2 × (22/7) × r × 14 = 88 => 88r = 88 => r = 1 cm. Diameter = 2 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A solid toy is in the form of a hemisphere surmounted by a right circular cone. The height of the cone is 2 cm and the diameter of the base is 4 cm. Determine the volume of the toy (take π = 3.14).",
    options: null,
    answer: "Volume of toy = 25.12 cm³.",
    explanation: "r = 2 cm, h = 2 cm. Volume = 1/3 π r² (h + 2r) = 1/3 × 3.14 × 4 × 6 = 25.12 cm³.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "A metallic sphere of radius 4.2 cm is melted and recast into the shape of a cylinder of radius 6 cm. Find the height of the cylinder.",
    options: null,
    answer: "Height of the cylinder = 2.744 cm.",
    explanation: "π R² h = 4/3 π r³ => 36 h = 4/3 (4.2)³ = 98.784 => h = 2.744 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 6,
    question: "A tent is in the shape of a cylinder surmounted by a conical top. If the height and diameter of the cylindrical part are 2.1 m and 4 m respectively, and the slant height of the top is 2.8 m, find the area of the canvas used for making the tent. Also, find the cost of the canvas at the rate of ₹ 500 per m².",
    options: null,
    answer: "Area = 44 m²; Cost = ₹ 22,000.",
    explanation: "Area = 2πrh + πrl = πr(2h + l) = (22/7)(2)(4.2 + 2.8) = (44/7)(7) = 44 m². Cost = 44 × 500 = ₹ 22,000.",
  },

  // --- 13. STATISTICS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The empirical relationship between the three measures of central tendency is:",
    options: [
      "A) 3 Median = Mode + 2 Mean",
      "B) Mode = 3 Mean - 2 Median",
      "C) 2 Median = 3 Mode - Mean",
      "D) Mean = 3 Median - 2 Mode"
    ],
    answer: "A) 3 Median = Mode + 2 Mean",
    explanation: "Karl Pearson's empirical formula is Mode = 3 Median - 2 Mean, which rearranges to 3 Median = Mode + 2 Mean.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the mode of the following distribution:\nMarks: 10-20, 20-30, 30-40, 40-50, 50-60\nFrequency: 4, 8, 12, 10, 6",
    options: null,
    answer: "Mode = 36.67",
    explanation: "Modal class is 30-40. l = 30, f1 = 12, f0 = 8, f2 = 10, h = 10. Mode = 30 + [(12-8)/(24-8-10)] × 10 = 30 + 6.67 = 36.67.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "The mean of the following frequency distribution is 18. Find the missing frequency f:\nClass: 11-13, 13-15, 15-17, 17-19, 19-21, 21-23, 23-25\nFrequency: 7, 6, 9, 13, f, 5, 4",
    options: null,
    answer: "Missing frequency f = 20.",
    explanation: "Sum fi*xi = 752 + 20f. Sum fi = 44 + f. Mean = (752 + 20f)/(44 + f) = 18 => 752 + 20f = 792 + 18f => 2f = 40 => f = 20.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "The median of the following data is 525. Find the values of x and y, if the total frequency is 100:\n0-100: 2, 100-200: 5, 200-300: x, 300-400: 12, 400-500: 17, 500-600: 20, 600-700: y, 700-800: 9, 800-900: 7, 900-1000: 4",
    options: null,
    answer: "x = 9, y = 15.",
    explanation: "Total frequency 76 + x + y = 100 => x + y = 24. Median 525 lies in 500-600. 525 = 500 + [(50 - (36 + x))/20] × 100 => 25 = (14 - x) × 5 => x = 9. Then y = 15.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 8,
    question: "The distribution below gives the weights of 30 students of a class. Find the mean and median of the data:\nWeight (kg): 40-45, 45-50, 50-55, 55-60, 60-65, 65-70, 70-75\nNumber of students: 2, 3, 8, 6, 6, 3, 2",
    options: null,
    answer: "Mean = 56.67 kg, Median = 56.67 kg.",
    explanation: "Mean = 1700/30 = 56.67 kg. Median class is 55-60: Median = 55 + [(15 - 13)/6] × 5 = 55 + 1.67 = 56.67 kg.",
  },

  // --- 14. PROBABILITY (6 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If P(E) = 0.05, what is the probability of 'not E'?",
    options: ["A) 0.95", "B) 0.05", "C) 1.05", "D) 0.50"],
    answer: "A) 0.95",
    explanation: "P(not E) = 1 - P(E) = 1 - 0.05 = 0.95.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following cannot be the probability of an event?",
    options: ["A) 2/3", "B) -1.5", "C) 15%", "D) 0.7"],
    answer: "B) -1.5",
    explanation: "Probability of any event must satisfy 0 ≤ P(E) ≤ 1. It cannot be negative.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A die is thrown once. Find the probability of getting: (i) a prime number, (ii) a number lying between 2 and 6.",
    options: null,
    answer: "(i) 1/2, (ii) 1/2.",
    explanation: "Total = 6. (i) Primes {2, 3, 5} => 3/6 = 1/2. (ii) Between 2 and 6 {3, 4, 5} => 3/6 = 1/2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "Two dice are thrown simultaneously. What is the probability of getting a doublet?",
    options: ["A) 1/6", "B) 1/12", "C) 1/36", "D) 5/36"],
    answer: "A) 1/6",
    explanation: "Total = 36. Doublets = 6 => 6/36 = 1/6.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "One card is drawn from a well-shuffled deck of 52 cards. Find the probability of getting: (i) a king of red colour, (ii) a face card, (iii) a spade.",
    options: null,
    answer: "(i) 1/26, (ii) 3/13, (iii) 1/4.",
    explanation: "(i) Red kings = 2/52 = 1/26. (ii) Face cards = 12/52 = 3/13. (iii) Spades = 13/52 = 1/4.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "A box contains 90 discs numbered 1 to 90. If one disc is drawn at random, find the probability that it bears: (i) a two-digit number, (ii) a perfect square number, (iii) a number divisible by 5.",
    options: null,
    answer: "(i) 9/10, (ii) 1/10, (iii) 1/5.",
    explanation: "Total = 90. (i) 10 to 90 = 81 => 81/90 = 9/10. (ii) Squares {1, 4, 9, 16, 25, 36, 49, 64, 81} = 9 => 9/90 = 1/10. (iii) Multiples of 5 = 18 => 18/90 = 1/5.",
  },

  // =========================================================================
  // ALTERNATIVE QUESTIONS FOR QUESTION SWAP & DIVERSITY
  // =========================================================================

  // --- Real Numbers Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The exponent of 2 in the prime factorisation of 144 is:",
    options: ["A) 4", "B) 5", "C) 6", "D) 3"],
    answer: "A) 4",
    explanation: "144 = 2⁴ × 3², so the exponent of 2 is 4.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the HCF and LCM of 96 and 404 using the Fundamental Theorem of Arithmetic.",
    options: null,
    answer: "HCF = 4, LCM = 9696.",
    explanation: "96 = 2⁵ × 3, 404 = 2² × 101. HCF = 2² = 4. LCM = (96 × 404)/4 = 9696.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Real Numbers",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If HCF(306, 657) = 9, find LCM(306, 657).",
    options: null,
    answer: "22338.",
    explanation: "LCM(a,b) = (a × b)/HCF(a,b) = (306 × 657)/9 = 34 × 657 = 22338.",
  },

  // --- Polynomials Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A quadratic polynomial whose zeroes are -4 and 3 is:",
    options: ["A) x² + x - 12", "B) x² - x + 12", "C) x² - x - 12", "D) x² + 7x + 12"],
    answer: "A) x² + x - 12",
    explanation: "Sum = -4 + 3 = -1, Product = -12. p(x) = x² - (Sum)x + Product = x² + x - 12.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the zeroes of the quadratic polynomial x² - 2x - 8.",
    options: null,
    answer: "The zeroes are 4 and -2.",
    explanation: "x² - 2x - 8 = (x - 4)(x + 2) = 0 => x = 4 or x = -2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Polynomials",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If α and β are the zeroes of the polynomial p(x) = 2x² - 4x + 5, evaluate α² + β².",
    options: null,
    answer: "-1.",
    explanation: "α + β = -(-4)/2 = 2, αβ = 5/2. α² + β² = (α + β)² - 2αβ = (2)² - 2(5/2) = 4 - 5 = -1.",
  },

  // --- Pair of Linear Equations in Two Variables Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If the lines given by 3x + 2ky = 2 and 2x + 5y + 1 = 0 are parallel, then the value of k is:",
    options: ["A) -5/4", "B) 2/5", "C) 15/4", "D) 3/2"],
    answer: "C) 15/4",
    explanation: "For parallel lines, 3/2 = 2k/5 => 4k = 15 => k = 15/4.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Solve the following pair of linear equations by elimination: x + y = 14 and x - y = 4.",
    options: null,
    answer: "x = 9, y = 5.",
    explanation: "Adding equations gives 2x = 18 => x = 9. Substituting x = 9 gives 9 + y = 14 => y = 5.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Pair of Linear Equations in Two Variables",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Solve for x and y: 2x + 3y = 11 and 2x - 4y = -24. Hence find the value of m for which y = mx + 3.",
    options: null,
    answer: "x = -2, y = 5, m = -1.",
    explanation: "Subtracting: 7y = 35 => y = 5. Then 2x + 15 = 11 => 2x = -4 => x = -2. 5 = m(-2) + 3 => -2m = 2 => m = -1.",
  },

  // --- Quadratic Equations Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The discriminant of the quadratic equation 2x² - 4x + 3 = 0 is:",
    options: ["A) -8", "B) 10", "C) -16", "D) 8"],
    answer: "A) -8",
    explanation: "D = b² - 4ac = (-4)² - 4(2)(3) = 16 - 24 = -8.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the roots of the quadratic equation x² - 3x - 10 = 0 by factorisation.",
    options: null,
    answer: "x = 5 and x = -2.",
    explanation: "x² - 5x + 2x - 10 = (x - 5)(x + 2) = 0 => x = 5, -2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Quadratic Equations",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find two consecutive positive integers, the sum of whose squares is 365.",
    options: null,
    answer: "The integers are 13 and 14.",
    explanation: "x² + (x + 1)² = 365 => 2x² + 2x - 364 = 0 => x² + x - 182 = 0 => (x + 14)(x - 13) = 0. Since positive, x = 13, next is 14.",
  },

  // --- Arithmetic Progressions Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The common difference of the AP: 1/p, (1-p)/p, (1-2p)/p, ... is:",
    options: ["A) p", "B) -p", "C) -1", "D) 1"],
    answer: "C) -1",
    explanation: "d = (1-p)/p - 1/p = (1 - p - 1)/p = -p/p = -1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Which term of the AP: 21, 18, 15, ... is -81?",
    options: null,
    answer: "The 35th term.",
    explanation: "a = 21, d = -3. an = a + (n - 1)d => -81 = 21 + (n - 1)(-3) => -102 = -3(n - 1) => n - 1 = 34 => n = 35.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Arithmetic Progressions",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find the sum of the first 22 terms of an AP in which d = 7 and 22nd term is 149.",
    options: null,
    answer: "1661.",
    explanation: "a22 = a + 21(7) = 149 => a = 149 - 147 = 2. S22 = 22/2 (a + l) = 11(2 + 149) = 11 × 151 = 1661.",
  },

  // --- Triangles Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In ABC, DE ∥ BC with D on AB and E on AC. If AD = 3 cm, DB = 2 cm, and AE = 6 cm, then EC is:",
    options: ["A) 4 cm", "B) 9 cm", "C) 5 cm", "D) 2.5 cm"],
    answer: "A) 4 cm",
    explanation: "By Thales Theorem, AD/DB = AE/EC => 3/2 = 6/EC => EC = (6 × 2)/3 = 4 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "In ABC, D and E are points on sides AB and AC such that AD = 1.5 cm, DB = 3 cm, AE = 1 cm, and EC = 2 cm. Check whether DE ∥ BC.",
    options: null,
    answer: "Yes, DE ∥ BC.",
    explanation: "AD/DB = 1.5/3 = 1/2. AE/EC = 1/2. Since AD/DB = AE/EC, by Converse of BPT, DE ∥ BC.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Triangles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A vertical pole of length 6 m casts a shadow 4 m long on the ground and at the same time a tower casts a shadow 28 m long. Find the height of the tower.",
    options: null,
    answer: "42 m.",
    explanation: "The triangles formed by pole/shadow and tower/shadow are similar (AA similarity). 6/h = 4/28 => h = (6 × 28)/4 = 42 m.",
  },

  // --- Coordinate Geometry Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The midpoint of the line segment joining P(-2, 8) and Q(-6, -4) is:",
    options: ["A) (-4, 2)", "B) (2, -4)", "C) (-4, 6)", "D) (-2, 4)"],
    answer: "A) (-4, 2)",
    explanation: "M = ((-2 + -6)/2, (8 + -4)/2) = (-8/2, 4/2) = (-4, 2).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the distance between the points P(2, 3) and Q(4, 1).",
    options: null,
    answer: "2√2 units.",
    explanation: "Distance = √((4 - 2)² + (1 - 3)²) = √(4 + 4) = √8 = 2√2 units.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Coordinate Geometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Find the ratio in which the y-axis divides the line segment joining the points (5, -6) and (-1, -4). Also find the point of intersection.",
    options: null,
    answer: "Ratio = 5 : 1, Point of intersection = (0, -13/3).",
    explanation: "Let point on y-axis be (0, y) dividing in k:1. x = (-k + 5)/(k + 1) = 0 => k = 5 (ratio 5:1). y = (5(-4) + 1(-6))/6 = -26/6 = -13/3.",
  },

  // --- Introduction to Trigonometry Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If sin A = 1/2, then the value of cot A is:",
    options: ["A) √3", "B) 1/√3", "C) 1/2", "D) 1"],
    answer: "A) √3",
    explanation: "sin A = 1/2 => A = 30°. cot 30° = √3.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Evaluate: 2 tan² 45° + cos² 30° - sin² 60°.",
    options: null,
    answer: "2.",
    explanation: "tan 45° = 1, cos 30° = √3/2, sin 60° = √3/2. Expression = 2(1)² + (3/4) - (3/4) = 2.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Introduction to Trigonometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove the identity: (sin θ + cosec θ)² + (cos θ + sec θ)² = 7 + tan² θ + cot² θ.",
    options: null,
    answer: "LHS = sin² θ + cosec² θ + 2 + cos² θ + sec² θ + 2 = (sin² θ + cos² θ) + 4 + (1 + cot² θ) + (1 + tan² θ) = 1 + 4 + 1 + 1 + tan² θ + cot² θ = 7 + tan² θ + cot² θ = RHS.",
    explanation: "Expanding squares and using standard Pythagorean trigonometric identities.",
  },

  // --- Some Applications of Trigonometry Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A ladder 10 m long reaches a window 8 m above the ground. The distance of the foot of the ladder from the base of the wall is:",
    options: ["A) 6 m", "B) 4 m", "C) 2√41 m", "D) 8 m"],
    answer: "A) 6 m",
    explanation: "By Pythagoras Theorem: d = √(10² - 8²) = √(100 - 64) = √36 = 6 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "An observer 1.5 m tall is 28.5 m away from a chimney. The angle of elevation of the top of the chimney from her eyes is 45°. What is the height of the chimney?",
    options: null,
    answer: "30 m.",
    explanation: "tan 45° = (h - 1.5)/28.5 => 1 = (h - 1.5)/28.5 => h - 1.5 = 28.5 => h = 30 m.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Some Applications of Trigonometry",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "From a point on a bridge across a river, the angles of depression of the banks on opposite sides of the river are 30° and 45° respectively. If the bridge is at a height of 3 m from the banks, find the width of the river.",
    options: null,
    answer: "3(1 + √3) m.",
    explanation: "Width = d1 + d2 = 3 cot 30° + 3 cot 45° = 3√3 + 3 = 3(1 + √3) m.",
  },

  // --- Circles Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A line intersecting a circle in two points is called a:",
    options: ["A) Tangent", "B) Secant", "C) Chord", "D) Diameter"],
    answer: "B) Secant",
    explanation: "A secant is a line that intersects a circle in two distinct points.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A tangent PQ at a point P of a circle of radius 5 cm meets a line through the centre O at a point Q so that OQ = 12 cm. Find the length PQ.",
    options: null,
    answer: "√119 cm.",
    explanation: "OP ⊥ PQ. PQ = √(OQ² - OP²) = √(12² - 5²) = √(144 - 25) = √119 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Circles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Prove that the parallelogram circumscribing a circle is a rhombus.",
    options: null,
    answer: "Let ABCD be a circumscribing parallelogram. AB = CD and AD = BC. Tangents from external points give AB + CD = AD + BC => 2AB = 2AD => AB = AD. Since adjacent sides are equal, ABCD is a rhombus.",
    explanation: "Equal tangent segment lengths applied around the circumscribed quadrilateral.",
  },

  // --- Areas Related to Circles Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The area of a quadrant of a circle whose circumference is 22 cm is (use π = 22/7):",
    options: ["A) 77/8 cm²", "B) 77/4 cm²", "C) 77/2 cm²", "D) 154 cm²"],
    answer: "A) 77/8 cm²",
    explanation: "2πr = 22 => r = 7/2 cm. Area of quadrant = 1/4 π r² = 1/4 × (22/7) × (49/4) = 77/8 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the area of a sector of a circle of radius 7 cm with central angle 90°.",
    options: null,
    answer: "38.5 cm².",
    explanation: "Area = (90/360) × π × r² = 1/4 × (22/7) × 49 = 77/2 = 38.5 cm².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Areas Related to Circles",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "The length of the minute hand of a clock is 14 cm. Find the area swept by the minute hand in 5 minutes. (use π = 22/7)",
    options: null,
    answer: "154/3 cm² (approx 51.33 cm²).",
    explanation: "In 60 min, angle = 360°, so in 5 min, angle = (360/60) × 5 = 30°. Area = (30/360) × (22/7) × 14 × 14 = (1/12) × 22 × 2 × 14 = 154/3 cm².",
  },

  // --- Surface Areas and Volumes Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If the radius of the base of a cone is halved, keeping the height same, what is the ratio of the volume of the reduced cone to that of the original cone?",
    options: ["A) 1 : 4", "B) 1 : 2", "C) 1 : 8", "D) 1 : 16"],
    answer: "A) 1 : 4",
    explanation: "V_original = 1/3 π r² h. V_new = 1/3 π (r/2)² h = 1/4 V_original. Ratio = 1 : 4.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A metallic sphere of radius 4.2 cm is melted and recast into the shape of a cylinder of radius 6 cm. Find the height of the cylinder.",
    options: null,
    answer: "2.744 cm.",
    explanation: "Volume of sphere = Volume of cylinder => 4/3 π (4.2)³ = π (6)² h => h = (4/3 × 74.088) / 36 = 2.744 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Surface Areas and Volumes",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A 20 m deep well with diameter 7 m is dug and the earth from digging is evenly spread out to form a platform 22 m by 14 m. Find the height of the platform.",
    options: null,
    answer: "2.5 m.",
    explanation: "Volume of earth dug = π r² h = (22/7) × (3.5)² × 20 = 770 m³. Volume of platform = 22 × 14 × H = 308 H = 770 => H = 770/308 = 2.5 m.",
  },

  // --- Statistics Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The empirical relationship between the three measures of central tendency is:",
    options: [
      "A) Mode = 3 Median - 2 Mean",
      "B) Mode = 2 Median - 3 Mean",
      "C) Median = 3 Mode - 2 Mean",
      "D) Mean = 3 Median - 2 Mode",
    ],
    answer: "A) Mode = 3 Median - 2 Mean",
    explanation: "Standard empirical relationship: 3 Median = Mode + 2 Mean => Mode = 3 Median - 2 Mean.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the mean of the first 5 natural numbers.",
    options: null,
    answer: "3.",
    explanation: "Mean = (1 + 2 + 3 + 4 + 5) / 5 = 15 / 5 = 3.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Statistics",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "If the mean of the observations x, x + 3, x + 5, x + 7, x + 10 is 9, find the value of x and hence the median.",
    options: null,
    answer: "x = 4, Median = 9.",
    explanation: "Sum = 5x + 25 = 5 × 9 = 45 => 5x = 20 => x = 4. Observations: 4, 7, 9, 11, 14. Middle value is 9.",
  },

  // --- Probability Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "If P(E) = 0.05, what is the probability of 'not E'?",
    options: ["A) 0.95", "B) 0.05", "C) 1.05", "D) 0"],
    answer: "A) 0.95",
    explanation: "P(not E) = 1 - P(E) = 1 - 0.05 = 0.95.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "A bag contains 3 red balls and 5 black balls. A ball is drawn at random from the bag. What is the probability that the ball drawn is (i) red, (ii) not red?",
    options: null,
    answer: "(i) 3/8, (ii) 5/8.",
    explanation: "Total balls = 8. (i) P(Red) = 3/8. (ii) P(Not Red) = 1 - 3/8 = 5/8.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "MATHEMATICS",
    topic: "Probability",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Two dice are thrown simultaneously. Find the probability that the sum of the numbers appearing on the dice is: (i) 7, (ii) greater than 10.",
    options: null,
    answer: "(i) 1/6, (ii) 1/12.",
    explanation: "Total = 36. (i) Sum 7 pairs: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6/36 = 1/6. (ii) Sum > 10 pairs: (5,6),(6,5),(6,6) = 3/36 = 1/12.",
  },
];

