import { QuestionInput } from "@/types/question";

export const SCIENCE_QUESTIONS: QuestionInput[] = [
  // --- 1. CHEMICAL REACTIONS AND EQUATIONS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following is a decomposition reaction?",
    options: [
      "A) 2Mg + O₂ → 2MgO",
      "B) CaCO₃ → CaO + CO₂",
      "C) Zn + CuSO₄ → ZnSO₄ + Cu",
      "D) Na₂SO₄ + BaCl₂ → BaSO₄ + 2NaCl"
    ],
    answer: "B) CaCO₃ → CaO + CO₂",
    explanation: "Thermal decomposition of calcium carbonate breaks down a single reactant into two simpler products (calcium oxide and carbon dioxide) upon heating.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why should a magnesium ribbon be cleaned with sandpaper before burning in air?",
    options: null,
    answer: "Magnesium ribbon is cleaned before burning to remove the protective layer of basic magnesium oxide formed on its surface due to reaction with atmospheric oxygen, allowing it to burn smoothly.",
    explanation: "Magnesium is a reactive metal that slowly forms an oxide layer on exposure to moist air, which prevents complete and smooth ignition until cleaned.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Translate the following into chemical equations and balance them:\n(a) Hydrogen gas combines with nitrogen to form ammonia.\n(b) Hydrogen sulphide gas burns in air to give water and sulphur dioxide.\n(c) Barium chloride reacts with aluminium sulphate to give aluminium chloride and barium sulphate.",
    options: null,
    answer: "(a) 3H₂ + N₂ → 2NH₃\n(b) 2H₂S + 3O₂ → 2H₂O + 2SO₂\n(c) 3BaCl₂ + Al₂(SO₄)₃ → 2AlCl₃ + 3BaSO₄",
    explanation: "Balancing ensures the Law of Conservation of Mass is obeyed with equal numbers of each element's atoms on reactant and product sides.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "In the reaction: CuO + H₂ → Cu + H₂O, which substance is oxidized and which is reduced?",
    options: [
      "A) H₂ is oxidized, CuO is reduced",
      "B) CuO is oxidized, H₂ is reduced",
      "C) Cu is oxidized, H₂O is reduced",
      "D) Both CuO and H₂ are oxidized"
    ],
    answer: "A) H₂ is oxidized, CuO is reduced",
    explanation: "H₂ gains oxygen to form H₂O (oxidation), while CuO loses oxygen to form Cu (reduction). This is a classic redox reaction.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What happens when an iron nail is dipped in copper sulphate solution? Write the balanced chemical equation and state the type of reaction.\n(b) Define rancidity and mention two methods used to prevent it in fat-containing foods.",
    options: null,
    answer: "(a) The blue colour of copper sulphate solution fades to light green due to formation of FeSO₄, and a brown coating of copper deposits on the iron nail. Equation: Fe (s) + CuSO₄ (aq) → FeSO₄ (aq) + Cu (s). Type: Displacement reaction.\n(b) Rancidity is the slow oxidation of fats and oils leading to foul smell and bad taste. Prevention methods: (i) Adding antioxidants like BHA/BHT, (ii) Flushing food packages with inert nitrogen gas, (iii) Refrigeration.",
    explanation: "Iron is more reactive than copper and displaces it from CuSO₄. Rancidity is prevented by mitigating atmospheric oxygen exposure.",
  },

  // --- 2. ACIDS, BASES AND SALTS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which gas is evolved when dilute hydrochloric acid reacts with zinc granules?",
    options: ["A) Carbon dioxide", "B) Hydrogen", "C) Chlorine", "D) Nitrogen"],
    answer: "B) Hydrogen",
    explanation: "Zn (s) + 2HCl (aq) → ZnCl₂ (aq) + H₂ (g). Hydrogen gas burns with a characteristic pop sound when tested with a burning splinter.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why does an aqueous solution of an acid conduct electricity, while dry HCl gas or glucose solution does not?",
    options: null,
    answer: "An aqueous solution of acid dissociates into free hydronium ions (H₃O⁺) and anions that carry electric current. In contrast, dry HCl gas does not ionize in the absence of water, and glucose is a covalent compound that does not form ions in solution.",
    explanation: "Electrical conductivity in aqueous solutions requires the presence and movement of mobile ions.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Five solutions A, B, C, D and E when tested with universal indicator showed pH of 4, 1, 11, 7 and 9 respectively. Which solution is:\n(a) Neutral?\n(b) Strongly alkaline?\n(c) Strongly acidic?\n(d) Weakly acidic?\n(e) Weakly alkaline?",
    options: null,
    answer: "(a) Neutral: D (pH = 7)\n(b) Strongly alkaline: C (pH = 11)\n(c) Strongly acidic: B (pH = 1)\n(d) Weakly acidic: A (pH = 4)\n(e) Weakly alkaline: E (pH = 9)",
    explanation: "pH 7 is neutral; pH < 7 is acidic (lower pH = stronger acid); pH > 7 is basic/alkaline (higher pH = stronger base).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "Write the chemical name, chemical formula, and two important uses for each of:\n(a) Bleaching powder\n(b) Plaster of Paris",
    options: null,
    answer: "(a) Bleaching powder: Calcium oxychloride, CaOCl₂. Uses: (i) Disinfecting drinking water, (ii) Bleaching cotton/linen in textile industry.\n(b) Plaster of Paris: Calcium sulphate hemihydrate, CaSO₄·1/2H₂O. Uses: (i) Setting fractured bones, (ii) Making decorative casts/toys.",
    explanation: "Bleaching powder is prepared by passing chlorine gas over dry slaked lime Ca(OH)₂. Plaster of Paris is formed by heating gypsum CaSO₄·2H₂O to 373 K.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is the chlor-alkali process? Write the balanced chemical equation and identify the products formed at anode, cathode, and in solution.\n(b) Why is baking powder preferred over baking soda for baking cakes?",
    options: null,
    answer: "(a) The chlor-alkali process is the electrolysis of concentrated aqueous sodium chloride (brine). Equation: 2NaCl (aq) + 2H₂O (l) → 2NaOH (aq) + Cl₂ (g) + H₂ (g). At Anode: Cl₂ gas; At Cathode: H₂ gas; In solution: NaOH.\n(b) Baking soda (NaHCO₃) decomposes on heating to give Na₂CO₃ which tastes bitter. Baking powder contains baking soda mixed with a mild edible acid (like tartaric acid) that neutralizes sodium carbonate and releases CO₂, making the cake soft and spongy without bitterness.",
    explanation: "Commercial industrial process for caustic soda, chlorine, and hydrogen; culinary chemistry of tartaric acid neutralization.",
  },

  // --- 3. METALS AND NON-METALS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following metals is stored under kerosene oil to prevent accidental fires?",
    options: ["A) Magnesium", "B) Sodium", "C) Copper", "D) Iron"],
    answer: "B) Sodium",
    explanation: "Sodium is an extremely reactive alkali metal that catches fire spontaneously upon contact with moisture and atmospheric oxygen. Hence it is stored under kerosene.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What are amphoteric oxides? Give two chemical equations demonstrating the amphoteric nature of aluminium oxide (Al₂O₃).",
    options: null,
    answer: "Amphoteric oxides are metal oxides that react with both acids and bases to produce salt and water.\n1. Reaction with acid: Al₂O₃ + 6HCl → 2AlCl₃ + 3H₂O\n2. Reaction with base: Al₂O₃ + 2NaOH → 2NaAlO₂ (Sodium aluminate) + H₂O",
    explanation: "Al₂O₃ exhibits dual acidic and basic chemical behavior depending on the reacting partner.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Differentiate between roasting and calcination with one balanced chemical equation for each process.",
    options: null,
    answer: "1. Roasting: Heating sulphide ores strongly in the presence of excess air to convert them into oxides.\nEquation: 2ZnS + 3O₂ → 2ZnO + 2SO₂\n2. Calcination: Heating carbonate ores strongly in limited or absent air to decompose them into oxides.\nEquation: ZnCO₃ → ZnO + CO₂",
    explanation: "Key metallurgical distinction between sulphide ore oxidation (roasting) and carbonate ore thermal decomposition (calcination).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "An alloy of copper and zinc is known as:",
    options: ["A) Bronze", "B) Brass", "C) Solder", "D) Amalgam"],
    answer: "B) Brass",
    explanation: "Brass is an alloy of Copper (Cu) and Zinc (Zn). Bronze is an alloy of Copper and Tin (Sn).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Show the formation of magnesium chloride (MgCl₂) by the transfer of electrons between magnesium (atomic number 12) and chlorine (atomic number 17).\n(b) List three general properties of ionic compounds.",
    options: null,
    answer: "(a) Mg (2,8,2) loses 2e⁻: Mg → Mg²⁺ + 2e⁻. 2Cl (2,8,7) gain 2e⁻: 2Cl + 2e⁻ → 2Cl⁻. Formula: Mg²⁺[Cl⁻]₂.\n(b) Properties: (i) High melting and boiling points, (ii) Hard and brittle crystalline solids, (iii) Conduct electricity in aqueous solution or molten state.",
    explanation: "Lewis electron dot representation of ionic bond formation and macroscopic properties resulting from crystal lattice structure.",
  },

  // --- 4. CARBON AND ITS COMPOUNDS (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The functional group present in propanone (CH₃COCH₃) is:",
    options: ["A) Alcohol", "B) Aldehyde", "C) Ketone", "D) Carboxylic acid"],
    answer: "C) Ketone",
    explanation: "Propanone contains the carbonyl group (>C=O) attached to two carbon atoms, which defines a ketone.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What are homologous series of carbon compounds? Mention any two characteristics.",
    options: null,
    answer: "A homologous series is a group of carbon compounds having the same functional group and similar chemical properties in which successive members differ by a -CH₂- unit and 14 u in molecular mass.\nCharacteristics: (i) Gradual gradation in physical properties, (ii) Similar chemical properties.",
    explanation: "Members share the general molecular formula, differing sequentially by methylene (-CH₂-) groups.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain the mechanism of the cleaning action of soaps with the help of a micelle concept.",
    options: null,
    answer: "A soap molecule has a hydrophobic hydrocarbon tail and a hydrophilic ionic head. In water, soap molecules align radially into spherical micelles, trapping oily dirt at the center. When agitated and rinsed with water, the micelles stay suspended in water and carry the dirt away.",
    explanation: "Amphipathic nature of soap enables emulsification of non-polar oil droplets in polar aqueous solvents.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "Write balanced chemical equations for the following reactions of ethanol:\n(a) Combustion in air\n(b) Reaction with sodium metal\n(c) Dehydration with concentrated sulphuric acid at 443 K\n(d) Oxidation with alkaline KMnO₄",
    options: null,
    answer: "(a) C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O + heat\n(b) 2C₂H₅OH + 2Na → 2C₂H₅ONa (Sodium ethoxide) + H₂ ↑\n(c) C₂H₅OH (conc. H₂SO₄, 443 K) → CH₂=CH₂ (Ethene) + H₂O\n(d) C₂H₅OH + 2[O] (alk. KMnO₄) → CH₃COOH (Ethanoic acid) + H₂O",
    explanation: "Core organic transformations prescribed in the CBSE Class 10 carbon syllabus.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is an esterification reaction? Write the chemical equation for the reaction between ethanol and ethanoic acid in the presence of concentrated H₂SO₄.\n(b) What is saponification? Write the corresponding equation.\n(c) Why is carbon tetravalent and capable of forming a vast number of compounds?",
    options: null,
    answer: "(a) Esterification: CH₃COOH + C₂H₅OH (conc. H₂SO₄) → CH₃COOC₂H₅ + H₂O.\n(b) Saponification: CH₃COOC₂H₅ + NaOH → CH₃COONa + C₂H₅OH.\n(c) Carbon forms millions of compounds due to (i) Catenation (self-linking ability to form long chains/rings) and (ii) Tetravalency (valency of 4 allowing bonds with diverse elements).",
    explanation: "Industrial and organic mechanisms of ester/soap production and fundamental uniqueness of carbon bonding.",
  },

  // --- 5. LIFE PROCESSES (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In humans, the breakdown of pyruvate to give carbon dioxide, water and energy takes place in the:",
    options: ["A) Cytoplasm", "B) Mitochondria", "C) Chloroplast", "D) Nucleus"],
    answer: "B) Mitochondria",
    explanation: "Aerobic respiration breaks down 3-carbon pyruvate into CO₂, H₂O and 36-38 ATP molecules inside the mitochondria.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why is double circulation necessary in human beings?",
    options: null,
    answer: "Double circulation keeps oxygenated and deoxygenated blood completely separated in 4-chambered human hearts. This provides high efficiency in oxygen supply, which is essential to meet the high energy demands needed to maintain constant body temperature (warm-blooded physiology).",
    explanation: "Prevents mixing of blood streams, ensuring maximum oxygen delivery for homeothermic cellular metabolism.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Describe the three major steps that take place during the process of photosynthesis in green plants.",
    options: null,
    answer: "1. Absorption of light energy by chlorophyll.\n2. Conversion of light energy into chemical energy and splitting of water molecules into hydrogen and oxygen (photolysis).\n3. Reduction of carbon dioxide to carbohydrates (glucose).",
    explanation: "Light and dark phase photosynthetic reactions converting inorganic solar energy into organic chemical energy.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "Explain the structure and functioning of a nephron in human kidneys with reference to glomerular filtration and selective reabsorption.",
    options: null,
    answer: "Structure: A nephron consists of a Bowman's capsule enclosing a glomerulus, followed by a convoluted renal tubule and collecting duct.\nFunctioning:\n1. Ultrafiltration: High-pressure filtration of water, glucose, amino acids, salts, and urea into Bowman's capsule.\n2. Selective Reabsorption: Useful substances (glucose, amino acids, water) are reabsorbed along the tubule into peritubular capillaries.\n3. Secretion & Excretion: Urine containing urea and uric acid enters the collecting duct.",
    explanation: "Physiological mechanism of blood purification and osmoregulation by functional units of the kidney.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Explain the digestion of carbohydrates, proteins and fats in the small intestine.\n(b) What is the role of bile juice and pancreatic enzymes in digestion?",
    options: null,
    answer: "(a) In small intestine:\n- Carbohydrates: Pancreatic amylase converts complex carbs to glucose.\n- Proteins: Trypsin breaks proteins into amino acids.\n- Fats: Emulsified by bile salts, digested by pancreatic lipase into fatty acids and glycerol.\n(b) Bile juice makes acidic chyme alkaline and emulsifies fats. Pancreatic enzymes provide trypsin, amylase, and lipase.",
    explanation: "Complete breakdown of macronutrients in duodenum and ileum mediated by liver secretions and pancreatic enzymes.",
  },

  // --- 6. CONTROL AND COORDINATION (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which plant hormone is primarily responsible for promoting cell division in fruits and seeds?",
    options: ["A) Auxin", "B) Gibberellin", "C) Cytokinin", "D) Abscisic acid"],
    answer: "C) Cytokinin",
    explanation: "Cytokinins promote active cell division (cytokinesis) and are found in greater concentrations in areas of rapid cell division like fruits and seeds.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is a reflex arc? Trace the sequence of events when your hand accidentally touches a hot object.",
    options: null,
    answer: "A reflex arc is the neural pathway that mediates a reflex action.\nPathway: Receptor (heat receptors in skin) → Sensory neuron → Spinal cord (Relay neuron) → Motor neuron → Effector (arm muscles contract to withdraw hand immediately).",
    explanation: "Involuntary, instantaneous protective mechanism mediated directly via spinal cord circuits bypassing conscious brain processing.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Name the hormones secreted by the following endocrine glands and state one function of each:\n(a) Thyroid gland\n(b) Pancreas\n(c) Adrenal gland",
    options: null,
    answer: "(a) Thyroid: Thyroxin — regulates carbohydrate, protein, and fat metabolism for optimal growth.\n(b) Pancreas: Insulin — regulates and lowers blood glucose levels.\n(c) Adrenal: Adrenaline — prepares the body for emergency 'fight or flight' response.",
    explanation: "Essential hormonal homeostasis and metabolic control in human physiology.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "(a) How do auxins promote phototropism in a plant stem bending towards unilateral light?\n(b) Which hormone is known as the stress/growth inhibitor hormone in plants and why?",
    options: null,
    answer: "(a) Auxin is synthesized at shoot tips. Unilateral light causes auxin to diffuse to the shaded side. Higher auxin concentration on the shaded side causes cells to elongate faster than on the illuminated side, causing the stem to bend towards light.\n(b) Abscisic acid (ABA) is the growth inhibitor / stress hormone. It inhibits growth and promotes stomatal closure during water stress.",
    explanation: "Mechanism of auxin differential elongation and abscisic acid stress adaptation.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Describe the structure of a neuron and explain how an electrical nerve impulse is transmitted across a synapse.\n(b) Name the parts of the human brain responsible for: (i) voluntary actions and thinking, (ii) maintaining posture and balance, (iii) regulating involuntary actions like blood pressure and salivation.",
    options: null,
    answer: "(a) Neuron consists of Cyton, Dendrites, Axon, and Nerve endings. At synaptic cleft, electrical impulse triggers release of chemical neurotransmitters which diffuse across and bind to dendrite receptors of the next neuron to generate a new electrical impulse.\n(b) (i) Cerebrum (Forebrain), (ii) Cerebellum (Hindbrain), (iii) Medulla oblongata (Hindbrain).",
    explanation: "Electrochemical neurotransmission across synapses and functional localization of cerebral and cerebellar brain centers.",
  },

  // --- 7. HOW DO ORGANISMS REPRODUCE? (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Asexual reproduction in yeast takes place by the process of:",
    options: ["A) Binary fission", "B) Budding", "C) Spore formation", "D) Fragmentation"],
    answer: "B) Budding",
    explanation: "Yeast reproduces asexually by budding, where a small outgrowth (bud) develops on the parent cell, matures, and eventually detaches.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is the difference between binary fission and multiple fission? Give one example of each.",
    options: null,
    answer: "Binary fission: Parent divides into two equal daughter cells (e.g. Amoeba).\nMultiple fission: Parent divides simultaneously into many daughter cells inside a protective cyst (e.g. Plasmodium).",
    explanation: "Cytoplasmic and nuclear division modes in single-celled organisms.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain the process of double fertilization in flowering plants.",
    options: null,
    answer: "Pollen tube releases two male gametes into embryo sac:\n1. Syngamy: One male gamete fuses with egg cell to form diploid zygote.\n2. Triple Fusion: Second male gamete fuses with two polar nuclei to form triploid primary endosperm nucleus (PEN).",
    explanation: "Characteristic reproductive mechanism in angiosperms ensuring both embryo formation and food reserve endosperm synthesis.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "(a) What is placenta? State its two main physiological functions in human reproduction.\n(b) List any two surgical methods of contraception in humans.",
    options: null,
    answer: "(a) Placenta is a specialized vascular tissue connecting fetus to uterine wall. Functions: (i) Transports oxygen and nutrients from mother to fetus, (ii) Removes CO₂ and nitrogenous wastes from fetal blood into maternal circulation.\n(b) Surgical methods: Vasectomy (males) and Tubectomy (females).",
    explanation: "Embryonic exchange interface and permanent family planning interventions.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Describe the path of the egg from ovary to uterus in the human female reproductive system.\n(b) What happens when the egg is not fertilized?",
    options: null,
    answer: "(a) Ovary releases mature ovum → picked up by Fallopian tube (oviduct) where fertilization occurs → travels to Uterus for implantation.\n(b) If unfertilized, corpus luteum degenerates, progesterone falls, and the endometrial lining sheds along with blood and mucus through vagina as menstruation (lasting 3-5 days).",
    explanation: "Ovarian and menstrual cycle physiology in the human female reproductive tract.",
  },

  // --- 8. HEREDITY (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A cross between a tall pea plant (TT) and a short pea plant (tt) resulted in progeny that were all tall because:",
    options: [
      "A) Tallness is the dominant trait",
      "B) Shortness is the dominant trait",
      "C) Tallness is the recessive trait",
      "D) Height of plant is not governed by genes"
    ],
    answer: "A) Tallness is the dominant trait",
    explanation: "In heterozygous Tt offspring (F1 generation), the allele for tallness (T) masks the expression of the recessive allele (t), expressing only the dominant tall phenotype.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Explain why the phenotypic ratio in the F2 generation of a monohybrid cross is 3 : 1 while the genotypic ratio is 1 : 2 : 1.",
    options: null,
    answer: "Self-pollination of F1 (Tt) yields 1 TT, 2 Tt, 1 tt. TT and Tt both produce tall plants, giving 3 tall : 1 dwarf phenotypic ratio. The genotypic breakdown is 1 TT : 2 Tt : 1 tt.",
    explanation: "Mendelian law of segregation demonstrated through monohybrid Punnett square.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "How is the sex of a child determined genetically in human beings?",
    options: null,
    answer: "Mother provides X chromosome. Father provides either X or Y chromosome (50% each). Fertilization of egg (X) by X-sperm gives female (XX); by Y-sperm gives male (XY). Hence paternal chromosome determines child's sex.",
    explanation: "Chromosomal sex determination showing 1:1 statistical probability of male and female offspring.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "In a dihybrid cross between a pea plant with round yellow seeds (RRYY) and wrinkled green seeds (rryy), what will be the phenotypes and ratios obtained in the F2 generation? State the Mendel's law derived from this cross.",
    options: null,
    answer: "F2 phenotypic ratio is 9 Round Yellow : 3 Round Green : 3 Wrinkled Yellow : 1 Wrinkled Green. Law derived: Law of Independent Assortment.",
    explanation: "Dihybrid inheritance illustrating non-linked independent assortment of seed shape and seed colour genes.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) A man with blood group A marries a woman with blood group O and their daughter has blood group O. What are the genotypes of father, mother and daughter?\n(b) Differentiate between acquired traits and inherited traits with two examples each.",
    options: null,
    answer: "(a) Father: I^A i (heterozygous A), Mother: ii (homozygous O), Daughter: ii (blood group O, receiving 'i' from each parent).\n(b) Inherited traits are coded in germ cell DNA and passed to offspring (e.g. eye colour, attached earlobes). Acquired traits develop over a lifetime without altering germline DNA (e.g. muscular strength, scar, swimming skill).",
    explanation: "ABO blood group genetics and fundamental distinction between somatic vs germline variation.",
  },

  // --- 9. LIGHT – REFLECTION AND REFRACTION (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A convex mirror of focal length f produces an image which is:",
    options: [
      "A) Real, inverted and magnified",
      "B) Virtual, erect and diminished",
      "C) Real, erect and same size",
      "D) Virtual, inverted and enlarged"
    ],
    answer: "B) Virtual, erect and diminished",
    explanation: "A convex mirror always forms a virtual, erect, and diminished image behind the mirror regardless of the object's position, providing a wider field of view.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the focal length of a lens of power -2.0 D. What type of lens is this?",
    options: null,
    answer: "f = 1/P = 1/(-2.0) = -0.5 m = -50 cm. It is a concave (diverging) lens.",
    explanation: "Negative focal length and negative power denote a concave lens.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A concave mirror produces three times magnified real image of an object placed at 10 cm in front of it. Where is the image located?",
    options: null,
    answer: "Image distance v = -30 cm (30 cm in front of the concave mirror).",
    explanation: "u = -10 cm, m = -3. m = -v/u => -3 = -v/(-10) => v = -30 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "A convex lens of focal length 15 cm forms an image 30 cm from the lens. Find the distance of the object from the lens. What is the magnification and nature of the image?",
    options: null,
    answer: "Object distance u = -30 cm, Magnification m = -1. The image is real, inverted, and of the same size as object.",
    explanation: "1/f = 1/v - 1/u => 1/15 = 1/30 - 1/u => 1/u = -1/30 => u = -30 cm. m = v/u = 30/(-30) = -1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) State Snell's law of refraction and define absolute refractive index of a medium.\n(b) Light enters from air to glass having refractive index 1.50. What is the speed of light in the glass? (Speed of light in vacuum = 3 × 10⁸ m/s).\n(c) Draw a ray diagram showing refraction of light through a rectangular glass slab and define lateral displacement.",
    options: null,
    answer: "(a) Snell's law: sin i / sin r = constant. Absolute refractive index n = c / v.\n(b) v = (3 × 10⁸ m/s) / 1.50 = 2 × 10⁸ m/s.\n(c) Lateral displacement is the perpendicular distance between the original direction of incident light ray and the emergent ray after passing through a glass slab.",
    explanation: "Snell's formulation, index of refraction calculation, and slab lateral displacement geometry.",
  },

  // --- 10. HUMAN EYE AND THE COLOURFUL WORLD (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Human Eye and the Colourful World",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The defect of vision in which a person cannot see distant objects clearly is called:",
    options: ["A) Hypermetropia", "B) Myopia", "C) Presbyopia", "D) Cataract"],
    answer: "B) Myopia",
    explanation: "Myopia (near-sightedness) is the refractive defect where near objects are clear but distant objects appear blurred because the image is focused in front of the retina.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Human Eye and the Colourful World",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why do stars twinkle while planets do not twinkle?",
    options: null,
    answer: "Stars are point sources situated far away; their light undergoes varying atmospheric refraction through air layers of changing densities, causing twinkling. Planets are closer extended sources; variations from different points average out to zero.",
    explanation: "Atmospheric refraction of point sources vs extended sources.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Human Eye and the Colourful World",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A person with a myopic eye cannot see objects beyond 1.2 m distinctly. What should be the type and power of the corrective lens to restore proper vision?",
    options: null,
    answer: "Corrective lens: Concave lens. Power P = -0.83 D.",
    explanation: "u = -∞, v = -1.2 m. 1/f = 1/v - 1/u => f = -1.2 m. P = 1/(-1.2) = -0.83 D.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Human Eye and the Colourful World",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "(a) What is dispersion of white light? Name the colour that deviates: (i) the most, (ii) the least, when passing through a glass prism.\n(b) Why does the clear sky appear blue during daytime and reddish at sunset?",
    options: null,
    answer: "(a) Dispersion: Splitting of white light into spectrum of 7 colours. Violet deviates most, Red deviates least.\n(b) Air molecules scatter shorter blue wavelengths strongly (Rayleigh scattering), giving blue sky. At sunset, light traverses thick atmosphere; blue light is scattered away, leaving only longer red wavelengths.",
    explanation: "Differential refractive indices for different wavelengths and Rayleigh scattering (I ∝ 1/λ⁴).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Human Eye and the Colourful World",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Describe hypermetropia (far-sightedness) and its correction using a convex lens.\n(b) State the two possible causes of hypermetropia.",
    options: null,
    answer: "(a) Hypermetropia is a condition where near objects are blurred because rays focus behind the retina. Corrected using a convex lens which provides required converging power.\n(b) Causes: (i) Focal length of eye lens is too long, (ii) Eyeball has become too short.",
    explanation: "Ray optics of hypermetropia and corrective convergence calculation.",
  },

  // --- 11. ELECTRICITY (6 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A piece of wire of resistance R is cut into five equal parts. These parts are then connected in parallel. If the equivalent resistance of this combination is R', then the ratio R/R' is:",
    options: ["A) 1/25", "B) 1/5", "C) 5", "D) 25"],
    answer: "D) 25",
    explanation: "Resistance of each piece = R/5. When 5 such pieces are connected in parallel: 1/R' = 1/(R/5) × 5 = 25/R. Therefore R/R' = 25.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State Ohm's law and write its mathematical equation with SI units of each quantity.",
    options: null,
    answer: "Ohm's Law: Current I is directly proportional to potential difference V across conductor ends at constant temperature. V = IR (V in Volts, I in Amperes, R in Ohms).",
    explanation: "Linear I-V relationship defining electrical resistance.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "An electric lamp of resistance 20 Ω and a conductor of 4 Ω resistance are connected in series to a 6 V battery. Calculate:\n(a) Total resistance of the circuit,\n(b) Current flowing through the circuit,\n(c) Potential difference across the electric lamp.",
    options: null,
    answer: "(a) Total resistance R = 24 Ω.\n(b) Current I = 6/24 = 0.25 A.\n(c) Potential difference across lamp V = 0.25 × 20 = 5 V.",
    explanation: "Series circuit rules: resistances add up, current is identical across all components, voltage divides proportionally.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 2,
    question: "How much electrical energy is consumed by an electric heater of 1000 W working for 2 hours daily in the month of June (30 days)?",
    options: ["A) 30 kWh", "B) 60 kWh", "C) 120 kWh", "D) 600 kWh"],
    answer: "B) 60 kWh",
    explanation: "Energy E = 1 kW × (2 × 30 h) = 60 kWh.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "A copper wire has diameter 0.5 mm and resistivity of 1.6 × 10⁻⁸ Ω·m. What will be the length of this wire to make its resistance 10 Ω? How much does the resistance change if the diameter is doubled?",
    options: null,
    answer: "Length l = 122.7 m. If diameter is doubled, cross-sectional area quadruples, reducing resistance to R/4 = 2.5 Ω.",
    explanation: "A = πr² = 1.9635 × 10⁻⁷ m². l = (10 × 1.9635 × 10⁻⁷)/(1.6 × 10⁻⁸) = 122.7 m. R ∝ 1/d².",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) State Joule's law of heating and derive H = I²Rt.\n(b) Why is tungsten used for lamp filaments?\n(c) Why are heating elements made of alloys rather than pure metals?",
    options: null,
    answer: "(a) Heat generated H = W = VIt = (IR)It = I²Rt.\n(b) Tungsten has high melting point (3380 °C) and glows without oxidizing easily.\n(c) Alloys (like Nichrome) have high resistivity and do not oxidize at high temperatures.",
    explanation: "Thermal physics of electrical dissipation, material selection for filaments, and resistive alloys.",
  },

  // --- 12. MAGNETIC EFFECTS OF ELECTRIC CURRENT (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The direction of magnetic field produced by a current-carrying straight conductor is determined by:",
    options: [
      "A) Fleming's Left-Hand Rule",
      "B) Right-Hand Thumb Rule",
      "C) Fleming's Right-Hand Rule",
      "D) Faraday's Law"
    ],
    answer: "B) Right-Hand Thumb Rule",
    explanation: "Right-Hand Thumb Rule: Thumb in current direction, curled fingers point in magnetic field lines direction.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State two properties of magnetic field lines. Why can no two field lines intersect each other?",
    options: null,
    answer: "1. Lines emerge from North and enter South outside a magnet.\n2. Closeness indicates field strength.\nLines cannot intersect because that would mean two different directions of magnetic field at one point, which is impossible.",
    explanation: "Vector property of magnetic field requiring a single unique direction at every point in space.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is a solenoid? State two factors on which the strength of magnetic field produced by a current-carrying solenoid depends.",
    options: null,
    answer: "A solenoid is a cylindrical coil of many tightly wrapped insulated wire turns. Field strength depends on: (i) Number of turns per unit length, (ii) Magnitude of current, (iii) Soft iron core.",
    explanation: "Electromagnetic induction principles in cylindrical coil geometries.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "State Fleming's Left-Hand Rule. A positively-charged alpha particle projected towards west is deflected towards north by a magnetic field. What is the direction of the magnetic field?",
    options: null,
    answer: "Fleming's Left-Hand Rule: Forefinger (Field), Middle finger (Current), Thumb (Force/Motion). With Current = West and Force = North, the Magnetic Field points upwards (vertically out of page).",
    explanation: "Lorentz magnetic force rule F = q(v × B) evaluated via Fleming's Left-Hand Rule.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is the function of an earth wire in domestic electrical circuits?\n(b) Explain the difference between short-circuiting and overloading.\n(c) What is the role of an electric fuse?",
    options: null,
    answer: "(a) Earth wire provides low-resistance path to ground for leakage currents, preventing severe shocks.\n(b) Short-circuiting is direct contact between live and neutral wires with near-zero resistance. Overloading is drawing more current than rated limit by running multiple high-power devices.\n(c) Fuse wire melts upon excessive current to break circuit and protect appliances.",
    explanation: "Domestic circuit safety mechanisms, earthing principles, and electrical safety standards.",
  },

  // --- 13. OUR ENVIRONMENT (5 Questions) ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following belongs to the same trophic level?",
    options: [
      "A) Grass, Grasshopper, Frog",
      "B) Hawk, Snake, Lizard",
      "C) Grasshopper, Rabbit, Deer",
      "D) Phytoplankton, Zooplankton, Fish"
    ],
    answer: "C) Grasshopper, Rabbit, Deer",
    explanation: "Grasshopper, Rabbit, and Deer are all primary consumers (herbivores) occupying the second trophic level (T2).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is the 10% law of energy transfer in an ecosystem? If 10,000 J of solar energy is captured by green plants, how much energy will be available to a hawk in: Plant → Grasshopper → Frog → Snake → Hawk?",
    options: null,
    answer: "10% Law: Only 10% energy transfers to next trophic level. Captured solar energy by plants = 100 J. Grasshopper = 10 J, Frog = 1 J, Snake = 0.1 J, Hawk = 0.01 J.",
    explanation: "Thermodynamic energy loss constraining trophic chain lengths to 4-5 levels.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is biological magnification? Will the level of biomagnification be different at different trophic levels of an ecosystem?",
    options: null,
    answer: "Biomagnification is progressive accumulation of non-biodegradable toxicants up a food chain. Concentration increases at each successive trophic level and is highest in top carnivores.",
    explanation: "Non-biodegradable contaminants cannot be metabolized or excreted, concentrating up the ecological pyramid.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 4,
    question: "(a) What is ozone and how is it formed in the upper atmosphere? Write the chemical reactions.\n(b) What causes the depletion of the ozone layer and what is the Montreal Protocol?",
    options: null,
    answer: "(a) O₂ + UV → O + O; O + O₂ → O₃ (Ozone).\n(b) Depleted by Chlorofluorocarbons (CFCs). Montreal Protocol (1987) is the global treaty freezing and phasing out CFCs.",
    explanation: "Stratospheric photochemistry, UV absorption mechanics, and global environmental governance.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Differentiate between biodegradable and non-biodegradable wastes with two examples of each.\n(b) Explain any three eco-friendly practices for municipal solid waste management.",
    options: null,
    answer: "(a) Biodegradable: Broken down by decomposers (e.g. food peels, paper). Non-biodegradable: Persist without decomposing (e.g. plastic, glass).\n(b) Practices: Source segregation, Composting of wet waste, Recycling of dry plastics/metals.",
    explanation: "Ecological impacts of solid waste streams and circular sustainability practices.",
  },

  // =========================================================================
  // ALTERNATIVE QUESTIONS FOR QUESTION SWAP & DIVERSITY
  // =========================================================================

  // --- Chemical Reactions and Equations Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following processes involves a chemical reaction?",
    options: [
      "A) Storing of oxygen gas under pressure in a gas cylinder",
      "B) Liquefaction of air",
      "C) Keeping petrol in a china dish in the open",
      "D) Heating copper wire in the presence of air at high temperature",
    ],
    answer: "D) Heating copper wire in the presence of air at high temperature",
    explanation: "Heating copper wire in air oxidises Cu to black CuO, which is a chemical reaction.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why is respiration considered an exothermic reaction? Explain.",
    options: null,
    answer: "During respiration, glucose combines with oxygen in the cells of our body to form carbon dioxide and water along with release of energy (ATP): C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy.",
    explanation: "Oxidation of carbohydrates yielding biochemical energy output.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is a redox reaction? Identify the substance oxidised, reduced, oxidising agent, and reducing agent in: MnO₂ + 4HCl → MnCl₂ + 2H₂O + Cl₂.",
    options: null,
    answer: "Redox reaction involves simultaneous oxidation and reduction. Substance oxidised: HCl (to Cl₂), Substance reduced: MnO₂ (to MnCl₂), Oxidising agent: MnO₂, Reducing agent: HCl.",
    explanation: "Electron transfer and hydrogen/oxygen transfer classification in redox systems.",
  },

  // --- Acids, Bases and Salts Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "What is the pH of pure water at 25°C?",
    options: ["A) 0", "B) 7", "C) 14", "D) 1"],
    answer: "B) 7",
    explanation: "Pure water is neutral with equal H⁺ and OH⁻ concentrations, having pH = 7.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why does dry HCl gas not change the colour of dry litmus paper?",
    options: null,
    answer: "Dry HCl gas does not furnish hydrogen ions (H⁺ or H₃O⁺) in the absence of water. Litmus color change occurs only in the presence of hydronium ions.",
    explanation: "Ionization of acids occurs strictly in aqueous medium.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Write balanced chemical equations for the preparation of Plaster of Paris from Gypsum and describe one important precaution during storage.",
    options: null,
    answer: "CaSO₄·2H₂O (373 K) → CaSO₄·½H₂O + 1½H₂O. Precaution: Must be stored in moisture-proof containers to prevent it from absorbing moisture and setting back into hard Gypsum.",
    explanation: "Thermal dehydration of calcium sulphate dihydrate at controlled temperature.",
  },

  // --- Metals and Non-metals Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following metals exists in the liquid state at room temperature?",
    options: ["A) Sodium", "B) Mercury", "C) Gallium", "D) Potassium"],
    answer: "B) Mercury",
    explanation: "Mercury (Hg) is the only transition metal liquid at ambient temperature.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why do ionic compounds have high melting and boiling points?",
    options: null,
    answer: "Ionic compounds have strong electrostatic forces of attraction between oppositely charged cations and anions in their crystal lattice, requiring large thermal energy to break.",
    explanation: "Lattice energy and strong ionic bond strength.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Differentiate between calcination and roasting with one balanced chemical equation for each.",
    options: null,
    answer: "Calcination: Heating carbonate ore in absence/limited air (e.g. ZnCO₃ → ZnO + CO₂). Roasting: Heating sulphide ore strongly in excess air (e.g. 2ZnS + 3O₂ → 2ZnO + 2SO₂).",
    explanation: "Pyrometallurgical extraction methods for carbonate and sulphide ores.",
  },

  // --- Carbon and its Compounds Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and its Compounds",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The general molecular formula of an alkyne homologous series is:",
    options: ["A) CnH2n+2", "B) CnH2n", "C) CnH2n-2", "D) CnH2n-1"],
    answer: "C) CnH2n-2",
    explanation: "Alkynes contain at least one carbon-carbon triple bond with general formula CₙH₂ₙ₋₂.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and its Compounds",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is a homologous series? State any two characteristics of its members.",
    options: null,
    answer: "A homologous series is a family of organic compounds having the same functional group and similar chemical properties, in which successive members differ by -CH₂- unit (14 u mass). Characteristics: (1) Same general formula, (2) Gradation in physical properties.",
    explanation: "Structural uniformity and regular chemical progression in organic taxonomy.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and its Compounds",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is saponification? Write a balanced chemical reaction showing the formation of soap from ethyl ethanoate.",
    options: null,
    answer: "Saponification is the alkaline hydrolysis of an ester into alcohol and sodium salt of carboxylic acid (soap): CH₃COOC₂H₅ + NaOH → CH₃COONa + C₂H₅OH.",
    explanation: "Ester hydrolysis in basic medium producing soap and alcohol.",
  },

  // --- Life Processes Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The breakdown of pyruvate to give carbon dioxide, water and energy takes place in:",
    options: ["A) Cytoplasm", "B) Mitochondria", "C) Chloroplast", "D) Nucleus"],
    answer: "B) Mitochondria",
    explanation: "Aerobic breakdown of pyruvate occurs inside the mitochondria matrix and inner membrane (Krebs cycle and ETS).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What are the necessary conditions for autotrophic nutrition and what are its by-products?",
    options: null,
    answer: "Conditions: Chlorophyll, Sunlight, Carbon dioxide (CO₂), and Water (H₂O). By-products: Oxygen gas (O₂) and water vapour.",
    explanation: "Photosynthetic machinery and metabolic precursors.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain the three main steps involved in the process of urine formation in humans.",
    options: null,
    answer: "(1) Glomerular filtration (ultrafiltration of nitrogenous wastes under pressure), (2) Tubular reabsorption (glucose, amino acids, salts, water reabsorbed in renal tubules), (3) Tubular secretion (excess ions secreted into filtrate).",
    explanation: "Renal physiology and homeostatic osmotic regulation.",
  },

  // --- Control and Coordination Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which plant hormone promotes rapid cell division, especially in fruits and seeds?",
    options: ["A) Auxin", "B) Gibberellin", "C) Cytokinin", "D) Abscisic acid"],
    answer: "C) Cytokinin",
    explanation: "Cytokinins promote cell division (cytokinesis) and are present in high concentrations in growing areas like seeds and fruits.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is a synapse? How does information travel across a synapse between two neurons?",
    options: null,
    answer: "A synapse is a microscopic gap between the axon terminal of one neuron and the dendrite of the next. Electrical impulses trigger release of chemical neurotransmitters which diffuse across the gap and generate a new electrical impulse in the next neuron.",
    explanation: "Neurochemical transmission across intercellular neural junctions.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Name the hormones secreted by thyroid, pancreas, and adrenal glands, and state one function of each in the human body.",
    options: null,
    answer: "(1) Thyroid: Thyroxin (regulates carbohydrate, protein, and fat metabolism), (2) Pancreas: Insulin (regulates blood glucose level), (3) Adrenal: Adrenaline (prepares body for fight or flight emergency responses).",
    explanation: "Endocrine gland functions and physiological homeostasis.",
  },

  // --- How do Organisms Reproduce? Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How do Organisms Reproduce?",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Asexual reproduction takes place through budding in:",
    options: ["A) Amoeba", "B) Yeast", "C) Plasmodium", "D) Leishmania"],
    answer: "B) Yeast",
    explanation: "Yeast (and Hydra) reproduce asexually by forming small outgrowth buds that detach upon maturity.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How do Organisms Reproduce?",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is the importance of DNA copying in reproduction?",
    options: null,
    answer: "DNA copying ensures the transmission of parental genetic characteristics to offspring while minor copying variations lead to evolutionary adaptation and species diversity.",
    explanation: "Genetic fidelity and evolutionary variations during cell division.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How do Organisms Reproduce?",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Distinguish between self-pollination and cross-pollination. How does a pollen tube facilitate fertilization?",
    options: null,
    answer: "Self-pollination: Transfer of pollen from anther to stigma of same flower. Cross-pollination: Transfer to stigma of different flower of same species. The pollen tube grows down the style into the ovary, delivering male gametes to the female egg cell in the ovule for syngamy.",
    explanation: "Angiosperm reproductive mechanics and fertilization pathways.",
  },

  // --- Heredity Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In a monohybrid cross between pure tall (TT) and pure dwarf (tt) pea plants, the phenotypic ratio in F2 generation is:",
    options: ["A) 3 : 1", "B) 1 : 2 : 1", "C) 9 : 3 : 3 : 1", "D) 1 : 1"],
    answer: "A) 3 : 1",
    explanation: "Mendel's monohybrid F2 generation produces 3 Tall (TT, Tt, Tt) : 1 Dwarf (tt).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "How is the sex of a child determined genetically in human beings?",
    options: null,
    answer: "Females have XX chromosomes and produce only X eggs. Males have XY chromosomes and produce 50% X and 50% Y sperms. Fertilization with X sperm gives female (XX); fertilization with Y sperm gives male (XY).",
    explanation: "Allosomal sex determination controlled by paternal gamete.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain Mendel's Law of Segregation with the help of a monohybrid cross Punnett square.",
    options: null,
    answer: "Law of Segregation: Alleles of a gene separate during gamete formation so each gamete carries only one allele. Cross: Tt × Tt → Gametes T, t. F2 offspring: TT (Tall), Tt (Tall), Tt (Tall), tt (Dwarf) in 1:2:1 genotypic and 3:1 phenotypic ratio.",
    explanation: "Allelic segregation during meiotic gametogenesis.",
  },

  // --- Light – Reflection and Refraction Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The focal length of a spherical mirror of radius of curvature 30 cm is:",
    options: ["A) 15 cm", "B) 30 cm", "C) 60 cm", "D) 10 cm"],
    answer: "A) 15 cm",
    explanation: "f = R / 2 = 30 / 2 = 15 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State Snell's law of refraction and express it in mathematical form.",
    options: null,
    answer: "Snell's Law: The ratio of the sine of angle of incidence to the sine of angle of refraction is constant for a given pair of media: sin i / sin r = constant = n₂₁.",
    explanation: "Fundamental law of wave refraction across optical boundaries.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A convex lens has a focal length of 20 cm. At what distance should an object be placed from the lens so that it forms a real and inverted image of the same size?",
    options: null,
    answer: "40 cm in front of the lens.",
    explanation: "An image of same size is formed when object is placed at 2F₁: u = -2f = -2(20) = -40 cm. By lens formula: 1/v - 1/u = 1/f => v = +40 cm.",
  },

  // --- The Human Eye and the Colourful World Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The change in focal length of an eye lens is caused by the action of the:",
    options: ["A) Pupil", "B) Retina", "C) Ciliary muscles", "D) Iris"],
    answer: "C) Ciliary muscles",
    explanation: "Ciliary muscles relax and contract to change the curvature and focal length of the crystalline eye lens (power of accommodation).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why do stars twinkle while planets do not?",
    options: null,
    answer: "Stars are point sources far away; their light undergoes continuous atmospheric refraction through turbulent air layers, causing fluctuating apparent brightness. Planets are extended sources, so point fluctuations average out.",
    explanation: "Atmospheric optical refraction on point vs extended astronomical sources.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is hypermetropia (far-sightedness)? State its two causes and name the type of lens used for its correction.",
    options: null,
    answer: "Hypermetropia is a defect where a person can see distant objects clearly but cannot see nearby objects distinctly. Causes: (1) Focal length of eye lens is too long, (2) Eyeball has become too small. Correction: Convex lens of suitable power.",
    explanation: "Refractive defect of the human eye and ophthalmic optical correction.",
  },

  // --- Electricity Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The SI unit of electrical resistivity is:",
    options: ["A) Ω", "B) Ω·m", "C) Ω/m", "D) A/m"],
    answer: "B) Ω·m",
    explanation: "Resistivity ρ = (R × A) / l has SI unit (Ω × m²)/m = Ω·m (Ohm-metre).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State Ohm's Law and write its mathematical formula.",
    options: null,
    answer: "Ohm's Law: The electric current flowing through a metallic conductor is directly proportional to the potential difference across its ends, provided temperature remains constant: V = I × R.",
    explanation: "Linear voltage-current relation in ohmic conductors.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Three resistors of resistances 2 Ω, 3 Ω, and 6 Ω are connected in parallel across a 6 V battery. Calculate: (i) the equivalent resistance, (ii) total circuit current.",
    options: null,
    answer: "(i) Equivalent resistance = 1 Ω, (ii) Total current = 6 A.",
    explanation: "1/Rp = 1/2 + 1/3 + 1/6 = 6/6 = 1 => Rp = 1 Ω. Total current I = V/Rp = 6/1 = 6 A.",
  },

  // --- Magnetic Effects of Electric Current Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The magnetic field inside a long straight current-carrying solenoid:",
    options: [
      "A) Is zero",
      "B) Decreases as we move towards its end",
      "C) Increases as we move towards its end",
      "D) Is the same at all points",
    ],
    answer: "D) Is the same at all points",
    explanation: "Inside a solenoid, magnetic field lines are straight and parallel, indicating uniform field strength.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State Fleming's Left-Hand Rule and name one device based on it.",
    options: null,
    answer: "Stretch thumb, forefinger, and middle finger mutually perpendicular: Forefinger in Magnetic field, Middle finger in Current, then Thumb points in direction of Force (Motion). Device: Electric Motor.",
    explanation: "Lorentz force vector alignment on current-carrying conductor in magnetic field.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is an electromagnet? List two factors on which the magnetic strength of a solenoid depends.",
    options: null,
    answer: "An electromagnet is a temporary magnet formed by placing a soft iron core inside a current-carrying solenoid. Factors: (1) Number of turns per unit length, (2) Magnitude of current flowing through the coil.",
    explanation: "Ferromagnetic core magnetization via solenoid field.",
  },

  // --- Our Environment Alternatives ---
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following is a non-biodegradable waste?",
    options: ["A) Fruit peel", "B) Plastic bag", "C) Paper cup", "D) Cotton cloth"],
    answer: "B) Plastic bag",
    explanation: "Plastic is synthetic polymer not decomposed by biological enzymes.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why are bacteria and fungi called decomposers? State their ecological importance.",
    options: null,
    answer: "They break down complex organic remains of dead plants and animals into simple inorganic substances that return to the soil and air, maintaining mineral recycling in ecosystems.",
    explanation: "Saprophytic enzymatic breakdown driving nutrient cycles.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Distinguish between a food chain and a food web with one suitable example of each.",
    options: null,
    answer: "Food chain: A single linear sequence of organisms where nutrients and energy pass from one to another (e.g., Grass → Deer → Tiger). Food web: A complex network of interconnected food chains representing all possible feeding relationships in an ecosystem.",
    explanation: "Ecological trophic network complexity and stability.",
  },
];

