import { QuestionInput } from "@/types/question";

export const EXPANDED_SCIENCE_QUESTIONS: QuestionInput[] = [
  // =========================================================================
  // 1. CHEMICAL REACTIONS AND EQUATIONS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following is an endothermic reaction?",
    options: ["A) Respiration", "B) Decomposition of calcium carbonate", "C) Burning of natural gas", "D) Dilution of sulphuric acid"],
    answer: "B) Decomposition of calcium carbonate",
    explanation: "Heating CaCO₃ requires thermal energy absorption to form CaO and CO₂, making it an endothermic decomposition reaction.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why is respiration considered an exothermic reaction? Explain with a chemical equation.",
    options: null,
    answer: "Respiration releases energy as glucose combines with oxygen: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + Energy.",
    explanation: "During digestion, food is broken down into glucose. In cells, glucose combines with oxygen to produce carbon dioxide, water, and heat/ATP energy.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "When lead nitrate powder is heated in a boiling tube, brown fumes are evolved. These brown fumes are of:",
    options: ["A) Lead oxide", "B) Nitrogen dioxide", "C) Oxygen", "D) Nitrous oxide"],
    answer: "B) Nitrogen dioxide",
    explanation: "2Pb(NO₃)₂ (s) —Heat→ 2PbO (s) + 4NO₂ (g) + O₂ (g). The brown gas evolved is nitrogen dioxide (NO₂).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A shiny brown coloured element 'X' on heating in air becomes black in colour. (i) Name the element 'X' and the black coloured compound formed. (ii) Write the balanced chemical equation for the reaction.",
    options: null,
    answer: "(i) Element 'X' is Copper (Cu). Black compound is Copper(II) oxide (CuO). (ii) 2Cu + O₂ —Heat→ 2CuO.",
    explanation: "Copper reacts with oxygen at high temperatures to form a black layer of copper(II) oxide on its surface.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Identify the substance oxidised, substance reduced, oxidising agent, and reducing agent in the reaction: MnO₂ + 4HCl → MnCl₂ + 2H₂O + Cl₂.",
    options: null,
    answer: "Substance oxidised: HCl (to Cl₂); Substance reduced: MnO₂ (to MnCl₂); Oxidising agent: MnO₂; Reducing agent: HCl.",
    explanation: "HCl loses hydrogen (oxidised), MnO₂ loses oxygen (reduced). The reactant causing oxidation is MnO₂, and the reactant causing reduction is HCl.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is a redox reaction? Explain with an example.\n(b) Explain two methods to prevent rancidity of fatty and oily foods.\n(c) Why do we apply paint on iron articles?",
    options: null,
    answer: "(a) A reaction in which oxidation and reduction take place simultaneously, e.g. CuO + H₂ → Cu + H₂O.\n(b) Methods: Adding antioxidants (e.g. BHA/BHT), packaging in nitrogen gas, or refrigeration.\n(c) Paint prevents contact with atmospheric moisture and oxygen, inhibiting corrosion/rusting.",
    explanation: "Comprehensive chemical explanation covering redox mechanics, lipid auto-oxidation prevention, and barrier protection against galvanic iron oxidation.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Translate the following statements into balanced chemical equations:\n(a) Hydrogen gas combines with nitrogen to form ammonia.\n(b) Hydrogen sulphide gas burns in air to give water and sulphur dioxide.\n(c) Barium chloride reacts with aluminium sulphate to give aluminium chloride and a precipitate of barium sulphate.\n(d) Potassium metal reacts with water to give potassium hydroxide and hydrogen gas.",
    options: null,
    answer: "(a) 3H₂ + N₂ → 2NH₃\n(b) 2H₂S + 3O₂ → 2H₂O + 2SO₂\n(c) 3BaCl₂ + Al₂(SO₄)₃ → 2AlCl₃ + 3BaSO₄↓\n(d) 2K + 2H₂O → 2KOH + H₂",
    explanation: "Standard stoichiometry balancing ensuring conservation of mass across all elemental species.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Chemical Reactions and Equations",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The chemical formula of rust is:",
    options: ["A) Fe₂O₃", "B) Fe₃O₄", "C) Fe₂O₃ · xH₂O", "D) Fe(OH)₃"],
    answer: "C) Fe₂O₃ · xH₂O",
    explanation: "Rust is hydrated iron(III) oxide with formula Fe₂O₃ · xH₂O.",
  },

  // =========================================================================
  // 2. ACIDS, BASES AND SALTS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following salts does not contain water of crystallisation?",
    options: ["A) Blue vitriol", "B) Baking soda", "C) Washing soda", "D) Gypsum"],
    answer: "B) Baking soda",
    explanation: "Baking soda is anhydrous NaHCO₃. Blue vitriol is CuSO₄·5H₂O, Washing soda is Na₂CO₃·10H₂O, and Gypsum is CaSO₄·2H₂O.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why does dry HCl gas not change the colour of dry litmus paper?",
    options: null,
    answer: "Dry HCl gas does not produce hydrogen (H⁺) or hydronium (H₃O⁺) ions in the absence of water. Acidic properties are manifested only when ions are present in aqueous solution.",
    explanation: "Litmus changes colour only in the presence of H⁺(aq) ions, which require an aqueous medium to dissociate.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "An aqueous solution turns red litmus paper blue. Excess addition of which of the following solution would reverse the change?",
    options: ["A) Baking powder", "B) Lime", "C) Ammonium hydroxide solution", "D) Hydrochloric acid"],
    answer: "D) Hydrochloric acid",
    explanation: "The initial solution is basic. Adding excess acid (HCl) neutralises the base and makes the solution acidic, turning blue litmus back to red.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Write the chemical formula and two major uses of (a) Bleaching powder, and (b) Plaster of Paris.",
    options: null,
    answer: "(a) Bleaching powder: CaOCl₂. Uses: Disinfectant for drinking water; bleaching cotton and linen in textile industry.\n(b) Plaster of Paris: CaSO₄·½H₂O. Uses: Setting fractured bones in plaster casts; making decorative moulds and statues.",
    explanation: "Commercial preparation and functional industrial applications of calcium oxychloride and calcium sulphate hemihydrate.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A compound 'X' of sodium is used as an antacid and in fire extinguishers. On heating, it gives compound 'Y' and a gas 'Z' which turns lime water milky. Identify X, Y, and Z, and write the reaction.",
    options: null,
    answer: "X = Sodium hydrogen carbonate (NaHCO₃), Y = Sodium carbonate (Na₂CO₃), Z = Carbon dioxide (CO₂). Reaction: 2NaHCO₃ —Heat→ Na₂CO₃ + H₂O + CO₂↑.",
    explanation: "Thermal decomposition of sodium bicarbonate produces anhydrous sodium carbonate, water vapour, and carbon dioxide gas.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is the chlor-alkali process? Name the three products formed and state one use of each.\n(b) Write the chemical equation for the chlor-alkali process.",
    options: null,
    answer: "(a) Chlor-alkali process is the electrolysis of aqueous sodium chloride (brine). Products: Chlorine gas (used in PVC/water treatment), Hydrogen gas (used in fuel/ammonia synthesis), and Sodium hydroxide solution (used in de-greasing metals/soap making).\n(b) 2NaCl(aq) + 2H₂O(l) → 2NaOH(aq) + Cl₂(g) + H₂(g).",
    explanation: "Electrolytic industrial production of caustic soda, chlorine, and hydrogen with anode/cathode product distribution.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) How is washing soda prepared from sodium chloride? Write balanced equations.\n(b) What is meant by water of crystallisation? Give two examples.",
    options: null,
    answer: "(a) Solvay process: NaCl + H₂O + CO₂ + NH₃ → NH₄Cl + NaHCO₃. 2NaHCO₃ —Heat→ Na₂CO₃ + H₂O + CO₂. Recrystallisation: Na₂CO₃ + 10H₂O → Na₂CO₃·10H₂O.\n(b) Water of crystallisation is the fixed number of water molecules present in one formula unit of a salt. Examples: CuSO₄·5H₂O, FeSO₄·7H₂O.",
    explanation: "Complete Solvay route synthesis of hydrated sodium carbonate and precise molecular definition of hydration water.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Acids, Bases and Salts",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The pH of a neutral solution at 25°C is:",
    options: ["A) 0", "B) 7", "C) 14", "D) 1"],
    answer: "B) 7",
    explanation: "At 25°C, [H⁺] = [OH⁻] = 10⁻⁷ M, hence pH = -log(10⁻⁷) = 7.",
  },

  // =========================================================================
  // 3. METALS AND NON-METALS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following metals exists in the liquid state at room temperature?",
    options: ["A) Sodium", "B) Mercury", "C) Potassium", "D) Bromine"],
    answer: "B) Mercury",
    explanation: "Mercury (Hg) is the only metal that is liquid at standard room temperature. (Bromine is a liquid non-metal).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why are ionic compounds usually hard and have high melting points?",
    options: null,
    answer: "Ionic compounds have strong electrostatic forces of attraction between oppositely charged cations and anions in their crystal lattice. A large amount of thermal energy is required to break these strong intermolecular ionic bonds.",
    explanation: "Coulombic ionic attractions across 3D crystal lattices require substantial enthalpy to disrupt.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "An alloy is:",
    options: ["A) An element", "B) A compound", "C) A homogeneous mixture", "D) A heterogeneous mixture"],
    answer: "C) A homogeneous mixture",
    explanation: "An alloy is a homogeneous mixture of two or more metals, or a metal and a non-metal.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Give reasons for the following:\n(a) Platinum, gold and silver are used to make jewellery.\n(b) Sodium and potassium are stored under kerosene oil.\n(c) Aluminium is a highly reactive metal, yet it is used to make utensils for cooking.",
    options: null,
    answer: "(a) Highly malleable, ductile, lustrous, and unreactive (corrosion resistant).\n(b) React vigorously with atmospheric oxygen and moisture catching fire spontaneously.\n(c) Forms a protective, impervious layer of aluminium oxide (Al₂O₃) preventing further corrosion.",
    explanation: "Chemical reactivity series and passivation oxide layers explaining metallurgical and domestic utility.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Differentiate between roasting and calcination with balanced chemical equations.",
    options: null,
    answer: "Calcination: Heating carbonate ore in the absence or limited supply of air, e.g. ZnCO₃ —Heat→ ZnO + CO₂↑.\nRoasting: Heating sulphide ore in the presence of excess air, e.g. 2ZnS + 3O₂ —Heat→ 2ZnO + 2SO₂↑.",
    explanation: "Metallurgical extraction operations comparing thermal carbonate decomposition vs oxidative sulphide roasting.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Explain the thermite process with a balanced chemical equation and state its industrial application.\n(b) Explain electrolytic refining of copper with a neat labelled schematic description (anode, cathode, electrolyte reactions).",
    options: null,
    answer: "(a) Thermite reaction is the reduction of iron(III) oxide by aluminium: Fe₂O₃(s) + 2Al(s) → 2Fe(l) + Al₂O₃(s) + Heat. The molten iron produced is used to join cracked railway tracks and heavy machine parts.\n(b) Anode: Impure copper rod (Cu → Cu²⁺ + 2e⁻). Cathode: Pure copper strip (Cu²⁺ + 2e⁻ → Cu). Electrolyte: Acidified CuSO₄ solution. Insoluble impurities settle as anode mud.",
    explanation: "Exothermic aluminothermic reduction and Faraday electro-refining cell dynamics for pure metal deposition.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Show the formation of Na₂O and MgO by the transfer of electrons. Identify the ions present in each compound.",
    options: null,
    answer: "Na (2,8,1) loses 1e⁻ to form Na⁺. O (2,6) gains 2e⁻ to form O²⁻. Two Na atoms transfer 1e⁻ each to one O atom forming Na₂O: 2Na⁺ + O²⁻.\nMg (2,8,2) loses 2e⁻ to form Mg²⁺. O gains 2e⁻ forming O²⁻: Mg²⁺ + O²⁻ forming MgO.",
    explanation: "Lewis dot electron-transfer mechanics leading to stable octet noble-gas configurations in ionic crystal units.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Metals and Non-metals",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following pairs will give displacement reactions?",
    options: ["A) NaCl solution and copper metal", "B) MgCl₂ solution and aluminium metal", "C) FeSO₄ solution and silver metal", "D) AgNO₃ solution and copper metal"],
    answer: "D) AgNO₃ solution and copper metal",
    explanation: "Copper is more reactive than silver and displaces it from AgNO₃ solution: Cu + 2AgNO₃ → Cu(NO₃)₂ + 2Ag.",
  },

  // =========================================================================
  // 4. CARBON AND ITS COMPOUNDS (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Cationic or anionic carbon ions (C⁴⁺ or C⁴⁻) are not formed because of:",
    options: ["A) High energy barrier to gain or lose 4 electrons", "B) Tetravalency", "C) Catenation property", "D) Isomerism"],
    answer: "A) High energy barrier to gain or lose 4 electrons",
    explanation: "Carbon cannot lose 4 electrons due to extremely high ionization energy, nor can a nucleus with 6 protons hold 10 electrons in C⁴⁻.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is a homologous series? State two characteristics of a homologous series.",
    options: null,
    answer: "A series of organic compounds having the same functional group and similar chemical properties in which successive members differ by a -CH₂- unit.\nCharacteristics: (i) Differ by 14 u in molecular mass, (ii) Show regular gradation in physical properties.",
    explanation: "Structural and physical property progression across alkane, alkene, alkyne, and alcohol families.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The structural formula of benzene is:",
    options: ["A) C₆H₆ with alternate single and double bonds", "B) C₆H₁₂ ring", "C) C₆H₁₄ straight chain", "D) C₆H₈ ring"],
    answer: "A) C₆H₆ with alternate single and double bonds",
    explanation: "Benzene has a cyclic hexagonal ring of 6 carbon atoms with alternate carbon-carbon single and double bonds and one hydrogen on each carbon.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain the mechanism of the cleaning action of soaps with the help of a labelled diagram/concept of micelles.",
    options: null,
    answer: "A soap molecule has a hydrophilic ionic head and a hydrophobic hydrocarbon tail. In water, tails cluster around oily/greasy dirt while heads face outward towards water forming a spherical micelle. Agitation pulls the micelle-trapped oily dirt into the water emulsion.",
    explanation: "Surfactant amphiphilic micelle formation dispersing hydrophobic grease in polar water.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "How would you distinguish experimentally between an alcohol and a carboxylic acid using sodium bicarbonate test and litmus paper test?",
    options: null,
    answer: "Sodium bicarbonate test: Carboxylic acid (ethanoic acid) produces brisk effervescence of CO₂ gas (turns lime water milky); Alcohol (ethanol) gives no reaction.\nLitmus test: Carboxylic acid turns blue litmus red; Alcohol has no effect on blue litmus.",
    explanation: "Acid-base reactivity and bicarbonate decomposition distinguishing weakly acidic alcohols from carboxylic acids.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is esterification? Write a chemical equation for the reaction of ethanol with ethanoic acid in the presence of concentrated H₂SO₄.\n(b) What is saponification? Write the corresponding equation.\n(c) What is the role of concentrated sulphuric acid in esterification?",
    options: null,
    answer: "(a) Esterification is the reaction between an alcohol and carboxylic acid to form a sweet-smelling ester: CH₃COOH + C₂H₅OH —Conc. H₂SO₄→ CH₃COOC₂H₅ + H₂O.\n(b) Saponification is the alkaline hydrolysis of an ester: CH₃COOC₂H₅ + NaOH → CH₃COONa + C₂H₅OH.\n(c) Concentrated H₂SO₄ acts as an acid catalyst and a dehydrating agent to absorb water and drive the equilibrium forward.",
    explanation: "Mechanistic treatment of reversible ester synthesis, acid dehydration, and alkaline soap hydrolysis.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Explain the following reactions with balanced equations:\n(a) Combustion of methane.\n(b) Oxidation of ethanol to ethanoic acid using alkaline KMnO₄.\n(c) Addition reaction of ethene with hydrogen in the presence of nickel catalyst.\n(d) Substitution reaction of methane with chlorine in the presence of sunlight.",
    options: null,
    answer: "(a) CH₄ + 2O₂ → CO₂ + 2H₂O + Heat + Light\n(b) CH₃CH₂OH —Alk. KMnO₄ + Heat→ CH₃COOH\n(c) CH₂=CH₂ + H₂ —Ni/473K→ CH₃-CH₃\n(d) CH₄ + Cl₂ —Sunlight→ CH₃Cl + HCl",
    explanation: "Foundational organic reactions: exothermic oxidation, catalytic hydrogenation, and radical halogenation.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Carbon and Its Compounds",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Ethanol on reaction with sodium metal produces sodium ethoxide and:",
    options: ["A) Carbon dioxide", "B) Hydrogen gas", "C) Oxygen gas", "D) Water"],
    answer: "B) Hydrogen gas",
    explanation: "2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂↑. Hydrogen gas burns with a characteristic pop sound.",
  },

  // =========================================================================
  // 5. LIFE PROCESSES (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The opening and closing of stomatal pores depends upon:",
    options: ["A) Oxygen concentration", "B) Temperature", "C) Water in guard cells", "D) Carbon dioxide concentration"],
    answer: "C) Water in guard cells",
    explanation: "Guard cells swell when water flows into them causing the stomatal pore to open, and shrink when they lose water causing the pore to close.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why do aquatic organisms breathe much faster than terrestrial organisms?",
    options: null,
    answer: "The amount of dissolved oxygen in water is fairly low compared to the amount of oxygen in the air (about 21%). Hence, aquatic organisms have to breathe much faster to obtain sufficient oxygen.",
    explanation: "Henry's law solubility limits oxygen availability in aquatic ecosystems relative to atmospheric partial pressure.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "In which part of the human alimentary canal is complete digestion of carbohydrates, proteins, and fats accomplished?",
    options: ["A) Stomach", "B) Small intestine", "C) Large intestine", "D) Liver"],
    answer: "B) Small intestine",
    explanation: "The small intestine receives secretions from the pancreas and liver (bile juice, pancreatic amylase, trypsin, lipase) and intestinal enzymes to complete digestion.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Describe the three pathways of glucose breakdown (glycolysis and subsequent fates in aerobic respiration, anaerobic yeast fermentation, and anaerobic muscle respiration).",
    options: null,
    answer: "In cytoplasm, 1 Glucose (6C) → 2 Pyruvate (3C) + Energy.\n(1) In yeast (Absence of O₂): Ethanol (2C) + CO₂ + Energy.\n(2) In muscle cells (Lack of O₂): Lactic acid (3C) + Energy (causes cramps).\n(3) In mitochondria (Presence of O₂): CO₂ + H₂O + Energy (36-38 ATP).",
    explanation: "Comparative metabolic pathways of cellular respiration in aerobic and anaerobic conditions.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What are the structural and functional adaptations of the small intestine for rapid and efficient absorption of digested food?",
    options: null,
    answer: "(1) Enormous surface area due to millions of microscopic finger-like projections called villi and microvilli.\n(2) Highly vascularised with a rich network of blood capillaries to carry absorbed nutrients.\n(3) Very thin, single-cell thick epithelial lining for rapid diffusion.",
    explanation: "Fick's law physiological adaptations maximising absorptive surface area and decreasing diffusion distance.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Describe double circulation in human beings. Why is it necessary to separate oxygenated and deoxygenated blood in mammals and birds?\n(b) Differentiate between arteries and veins.",
    options: null,
    answer: "(a) Blood passes through the heart twice during each complete cardiac cycle (Pulmonary circulation: Right ventricle → Lungs → Left atrium; Systemic circulation: Left ventricle → Body tissues → Right atrium). Separation prevents mixing of oxygenated and deoxygenated blood, ensuring highly efficient oxygen delivery to maintain constant high body temperature (homeothermy).\n(b) Arteries: Thick elastic walls, deep-seated, no valves, carry blood under high pressure away from heart. Veins: Thin walls, superficial, have pocket valves, carry blood toward heart.",
    explanation: "Cardiovascular hemodynamics, homeothermic metabolic demands, and histological vascular adaptations.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Describe the structure and functioning of a nephron in human kidneys. Explain how urine is produced (Ultrafiltration, Selective Reabsorption, Tubular Secretion).",
    options: null,
    answer: "Structure: Bowmans capsule enclosing Glomerulus, followed by proximal convoluted tubule (PCT), Loop of Henle, distal tubule (DCT), and collecting duct.\nFunctioning: (1) Glomerular Filtration: High blood pressure filters water, glucose, amino acids, urea, and salts into Bowmans capsule. (2) Selective Reabsorption: Useful substances (glucose, amino acids, major ions, water) are reabsorbed into peritubular capillaries. (3) Tubular Secretion: Excess K⁺, H⁺, and creatinine secreted into filtrate, forming final urine.",
    explanation: "Renal histology and counter-current physiological mechanisms of excretion and osmoregulation.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Life Processes",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Xylem in plants is primarily responsible for:",
    options: ["A) Transport of water and dissolved minerals", "B) Transport of food", "C) Transport of amino acids", "D) Transport of oxygen"],
    answer: "A) Transport of water and dissolved minerals",
    explanation: "Xylem vessels and tracheids transport water and dissolved inorganic minerals upward from roots via transpirational pull.",
  },

  // =========================================================================
  // 6. CONTROL AND COORDINATION (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which plant hormone promotes cell division and is present in high concentration in fruits and seeds?",
    options: ["A) Auxin", "B) Gibberellin", "C) Cytokinin", "D) Abscisic acid"],
    answer: "C) Cytokinin",
    explanation: "Cytokinins promote active cytokinesis (cell division) and are found in areas of rapid cell division like root tips, embryos, and young fruits.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is a reflex arc? Trace the sequence of events when your hand touches a hot object.",
    options: null,
    answer: "Reflex arc: Receptor (Skin heat sensors) → Sensory neuron → Spinal cord (Relay neuron) → Motor neuron → Effector (Biceps muscle contracts to pull hand away).",
    explanation: "Involuntary neural pathway bypassing conscious brain processing for instantaneous survival response.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The part of the human brain responsible for maintaining posture and balance of the body is:",
    options: ["A) Cerebrum", "B) Cerebellum", "C) Medulla", "D) Pons"],
    answer: "B) Cerebellum",
    explanation: "The cerebellum (hindbrain) coordinates voluntary motor movements, precision, equilibrium, and posture.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Name the endocrine gland associated with the following hormones and state one primary function of each: (a) Insulin, (b) Thyroxine, (c) Adrenaline.",
    options: null,
    answer: "(a) Pancreas: Insulin regulates blood glucose levels by promoting glucose uptake by cells.\n(b) Thyroid gland: Thyroxine regulates carbohydrate, protein, and fat metabolism for balanced growth.\n(c) Adrenal gland: Adrenaline prepares the body for 'fight or flight' emergency responses by increasing heart rate and blood flow.",
    explanation: "Endocrine physiology covering hormonal homeostasis and metabolic orchestration.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain how auxin promotes phototropism in a growing shoot bending towards unidirectional light.",
    options: null,
    answer: "When sunlight illuminates one side of a plant shoot, auxin synthesised at the shoot tip diffuses toward the shady side. The higher concentration of auxin on the shaded side stimulates cells there to elongate more rapidly than on the illuminated side, causing the shoot to bend towards the light.",
    explanation: "Auxin redistribution and asymmetric cellular elongation causing positive phototropic curvature.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Draw a neat labelled diagram of a neuron and describe how an electrical impulse travels through it and across a synapse.\n(b) Why is electrical transmission faster than chemical transmission?",
    options: null,
    answer: "(a) Dendrite tip receives stimulus → generates electrical nerve impulse → travels along Cell body → down Axon → at Axon terminal, electrical signal triggers release of neurotransmitters (e.g. acetylcholine) into Synapse → chemical diffuses across synaptic cleft → binds to receptors on next dendrite, initiating new electrical impulse.\n(b) Electrical impulses travel rapidly along continuous axon membranes via ion flux, whereas chemical transmission involves physical diffusion of neurotransmitter molecules across the synaptic gap.",
    explanation: "Neuroanatomy, action potential propagation, and neurotransmitter diffusion across synaptic clefts.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Differentiate between tropic movements and nastic movements in plants with two suitable examples of each.",
    options: null,
    answer: "Tropic movements: Directional growth movements determined by the direction of stimulus. Examples: (1) Phototropism (shoot bends toward light), (2) Geotropism (roots grow downward toward gravity).\nNastic movements: Non-directional, reversible turgor-driven movements independent of stimulus direction. Examples: (1) Thigmonasty in Mimosa pudica ('touch-me-not' leaves drop upon touch), (2) Nyctinasty (opening and closing of flower petals with day/night).",
    explanation: "Botanical comparison between irreversible directional growth vs reversible osmotic turgor alterations.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Control and Coordination",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Iodised salt is recommended in our diet to prevent:",
    options: ["A) Diabetes", "B) Goitre", "C) Scurvy", "D) Rickets"],
    answer: "B) Goitre",
    explanation: "Iodine is required by the thyroid gland to synthesise thyroxine hormone. Deficiency causes enlargement of thyroid (goitre).",
  },

  // =========================================================================
  // 7. HOW DO ORGANISMS REPRODUCE? (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Asexual reproduction through budding takes place in:",
    options: ["A) Amoeba", "B) Yeast", "C) Plasmodium", "D) Leishmania"],
    answer: "B) Yeast",
    explanation: "Yeast (and Hydra) reproduces asexually through budding, forming small outgrowths that detach into daughter individuals.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "What is pollination? Differentiate between self-pollination and cross-pollination.",
    options: null,
    answer: "Pollination is the transfer of pollen grains from the anther to the stigma of a flower.\nSelf-pollination: Transfer within the same flower or another flower on the same plant.\nCross-pollination: Transfer from the anther of one plant to the stigma of another plant of the same species.",
    explanation: "Angiosperm reproductive biology explaining pollen vector dynamics and genetic recombination.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "Which of the following contraceptive methods also prevents the transmission of Sexually Transmitted Infections (STIs)?",
    options: ["A) Copper-T", "B) Oral pills", "C) Condoms", "D) Tubectomy"],
    answer: "C) Condoms",
    explanation: "Condoms act as a mechanical barrier preventing direct physical and fluid contact, thereby protecting against STIs (like HIV, syphilis) and pregnancy.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain the structure and functions of the placenta during human pregnancy.",
    options: null,
    answer: "Placenta is a disc-like vascular tissue embedded in the uterine wall containing villi on the embryo side and blood spaces on the maternal side.\nFunctions: (1) Provides large surface area for glucose and oxygen transfer from mother to fetus, (2) Removes metabolic wastes (urea, CO₂) generated by fetus into maternal bloodstream.",
    explanation: "Fetomaternal physiological exchange interface and endocrine support.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Trace the path of sperms from the site of production to fertilisation in the female reproductive tract.",
    options: null,
    answer: "Testes (Seminiferous tubules) → Epididymis → Vas deferens → Urethra → Ejaculation into Vagina → Cervix → Uterus → Fallopian tube (Ampulla, where fertilisation with ovum occurs).",
    explanation: "Anatomical transit pathway of gametes in human male and female reproductive systems.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Describe the post-fertilisation changes that occur in a flower leading to seed and fruit formation.\n(b) Explain double fertilisation in angiosperms.",
    options: null,
    answer: "(a) Zygote divides to form embryo within ovule; Endosperm develops to nourish embryo; Ovule coat hardens into seed coat; Ovary ripens and develops into fruit; Petals, sepals, stamens wither and fall off.\n(b) Double fertilisation: Pollen tube releases two male gametes into embryo sac. One male gamete fuses with egg cell to form diploid zygote (Syngamy). Second male gamete fuses with diploid secondary nucleus to form triploid primary endosperm nucleus (Triple Fusion).",
    explanation: "Double fertilisation mechanism and carpel morphological transformation in angiosperm reproduction.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is vegetative propagation? Mention two advantages of this method.\n(b) Explain how regeneration in Planaria differs from reproduction in complex multicellular animals.",
    options: null,
    answer: "(a) Reproduction where new plants grow from vegetative parts (roots, stems, leaves) without seeds. Advantages: (1) Plants bear flowers/fruits earlier, (2) Offspring are genetically identical to parent (preserves desirable traits), (3) Can propagate seedless varieties (banana, rose).\n(b) Planaria has specialised regenerative stem cells that can proliferate and reconstruct complete bodies from severed pieces. Complex multicellular animals have highly differentiated tissue-organ hierarchies and cannot regenerate entire bodies from fragments.",
    explanation: "Asexual horticultural propagation and stem-cell morphogenesis comparison.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "How Do Organisms Reproduce?",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The female germ cell (egg) in human beings is produced in the:",
    options: ["A) Uterus", "B) Ovary", "C) Fallopian tube", "D) Cervix"],
    answer: "B) Ovary",
    explanation: "Ovaries produce mature female gametes (ova/eggs) and secrete female hormones estrogen and progesterone.",
  },

  // =========================================================================
  // 8. HEREDITY (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In Mendel's monohybrid cross between pure tall (TT) and pure dwarf (tt) pea plants, the phenotypic ratio in F₂ generation is:",
    options: ["A) 1 : 2 : 1", "B) 3 : 1", "C) 9 : 3 : 3 : 1", "D) 2 : 1"],
    answer: "B) 3 : 1",
    explanation: "Phenotypic ratio of F₂ is 3 Tall : 1 Dwarf. (Genotypic ratio is 1 TT : 2 Tt : 1 tt).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why did Gregor Mendel select garden pea plant (Pisum sativum) for his hybridization experiments?",
    options: null,
    answer: "(1) Easy to grow with a short life cycle.\n(2) Naturally self-pollinating but easy to cross-pollinate artificially.\n(3) Possesses distinct, easily observable contrasting characters (e.g. Tall/Dwarf, Round/Wrinkled seeds).",
    explanation: "Experimental model organism selection criteria in classical Mendelian genetics.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "A cross between a tall plant (TT) and short pea plant (tt) resulted in progeny that were all tall plants because:",
    options: ["A) Tallness is the dominant trait", "B) Shortness is the dominant trait", "C) Tallness is the recessive trait", "D) Height is not governed by genes"],
    answer: "A) Tallness is the dominant trait",
    explanation: "In heterozygous Tt condition, the allele for tallness (T) expresses itself and masks the recessive dwarf allele (t).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Explain how sex is determined genetically in human beings with the help of a Punnett square/flowchart.",
    options: null,
    answer: "Females carry XX chromosomes and produce only X-bearing eggs. Males carry XY chromosomes and produce 50% X-bearing and 50% Y-bearing sperms.\nIf an X-sperm fertilises the ovum: XX (Female child).\nIf a Y-sperm fertilises the ovum: XY (Male child).\nSex is determined entirely by the paternal sperm, with an equal 50:50 statistical probability.",
    explanation: "XX-XY chromosomal sex determination mechanisms in humans.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A man with blood group A marries a woman with blood group O and their daughter has blood group O. Is this information enough to tell you which of the traits — blood group A or O — is dominant? Why or why not?",
    options: null,
    answer: "No, this information alone is not sufficient to establish dominance. Blood group A can be homozygous (I^A I^A) or heterozygous (I^A i). Since daughter is group O (genotype ii), she inherited an 'i' allele from both parents, indicating the father is heterozygous I^A i. In ABO system, A is codominant/dominant and O is recessive, but the given cross alone only confirms father carries allele i.",
    explanation: "Genotypic analysis of ABO blood group alleles and inheritance patterns.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Explain Mendel's dihybrid cross with pure breeding plants having round yellow seeds (RRYY) and wrinkled green seeds (rryy). Show the gametes, F₁ generation, and the Punnett square for F₂ generation with phenotypic and genotypic ratios.",
    options: null,
    answer: "Parents: RRYY × rryy → Gametes: RY, ry → F₁: RrYy (All Round Yellow).\nSelfing F₁: Gametes RY, Ry, rY, ry.\nF₂ Phenotypes (16 boxes): 9 Round Yellow : 3 Round Green : 3 Wrinkled Yellow : 1 Wrinkled Green.\nLaw of Independent Assortment: Alleles of two different genes assort independently of one another during gamete formation.",
    explanation: "Classic dihybrid 9:3:3:1 Mendelian ratio and Law of Independent Assortment.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What are genes? Where are they located?\n(b) Differentiate between inherited traits and acquired traits with two examples of each.\n(c) Why are traits acquired during the lifetime of an individual not inherited?",
    options: null,
    answer: "(a) Genes are functional units of heredity consisting of DNA sequences located on chromosomes in the cell nucleus.\n(b) Inherited traits: Transferred genetically from parents to offspring (e.g. eye colour, earlobe attachment). Acquired traits: Developed during lifetime due to environmental influence or use/disuse (e.g. muscular strength, scar on skin).\n(c) Acquired traits cause changes only in non-reproductive somatic cells, not in the DNA of germ cells (gametes).",
    explanation: "Molecular basis of heredity and somatic vs germline inheritance principles.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Heredity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A zygote which has an X-chromosome inherited from the father will develop into a:",
    options: ["A) Girl", "B) Boy", "C) Either boy or girl", "D) Genetically undetermined"],
    answer: "A) Girl",
    explanation: "Mother always contributes an X chromosome. If father contributes an X chromosome, zygote is XX (Female/Girl).",
  },

  // =========================================================================
  // 9. LIGHT – REFLECTION AND REFRACTION (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "A concave mirror produces a real, inverted and equal sized image of an object when the object is placed at:",
    options: ["A) Focus F", "B) Centre of curvature C", "C) Between F and C", "D) Beyond C"],
    answer: "B) Centre of curvature C",
    explanation: "When object is placed at C of a concave mirror, image is also formed at C, real, inverted, and of magnification m = -1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Find the focal length of a convex mirror whose radius of curvature is 32 cm.",
    options: null,
    answer: "+16 cm",
    explanation: "Focal length f = R / 2 = +32 / 2 = +16 cm (positive for convex mirror).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "The refractive index of glass with respect to air is 3/2 and of water with respect to air is 4/3. The refractive index of glass with respect to water is:",
    options: ["A) 8/9", "B) 9/8", "C) 2", "D) 1/2"],
    answer: "B) 9/8",
    explanation: "w_n_g = n_g / n_w = (3/2) / (4/3) = (3/2) × (3/4) = 9/8.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A convex lens has a focal length of 20 cm. At what distance should an object be placed from the lens so that it forms a real and inverted image 40 cm away on the other side? Find the magnification.",
    options: null,
    answer: "Object distance u = -40 cm; Magnification m = -1",
    explanation: "Lens formula: 1/f = 1/v - 1/u => 1/20 = 1/40 - 1/u => 1/u = 1/40 - 1/20 = -1/40 => u = -40 cm. Magnification m = v/u = 40 / (-40) = -1.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A concave lens has focal length of 15 cm. At what distance should the object from the lens be placed so that it forms an image at 10 cm from the lens? Also, find the magnification produced by the lens.",
    options: null,
    answer: "u = -30 cm; m = +0.33",
    explanation: "Concave lens: f = -15 cm, v = -10 cm. 1/f = 1/v - 1/u => -1/15 = -1/10 - 1/u => 1/u = -1/10 + 1/15 = -1/30 => u = -30 cm. m = v/u = -10 / -30 = +1/3 = +0.33.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) State Snell's law of refraction.\n(b) A concave mirror produces three times magnified real image of an object placed at 10 cm in front of it. Where is the image located?\n(c) Define optical centre and power of a lens. What is the power of a combination of lenses of powers +2.0 D and -1.5 D?",
    options: null,
    answer: "(a) Snell's Law: sin i / sin r = constant = n₂₁ (refractive index).\n(b) u = -10 cm, m = -3 => -v/u = -3 => v = 3u = 3(-10) = -30 cm (30 cm in front of mirror).\n(c) Optical centre: Central point of a lens through which rays pass without deviation. Power P = 1/f(in metres). Net Power = P1 + P2 = +2.0 D - 1.5 D = +0.5 D.",
    explanation: "Comprehensive optics synthesis covering Snell's law, Cartesian sign convention, magnification, and lens power addition.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "An object 5 cm in length is held 25 cm away from a converging lens of focal length 10 cm. Draw the ray diagram and find the position, size, and the nature of the image formed.",
    options: null,
    answer: "Position: v = +16.67 cm behind the lens; Size: h' = -3.33 cm; Nature: Real, inverted and diminished.",
    explanation: "u = -25 cm, f = +10 cm, h = 5 cm. 1/v - 1/u = 1/f => 1/v - 1/(-25) = 1/10 => 1/v = 1/10 - 1/25 = 3/50 => v = 50/3 = +16.67 cm. m = v/u = (50/3)/(-25) = -2/3. h' = m × h = (-2/3) × 5 = -3.33 cm.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Light – Reflection and Refraction",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following lenses would you prefer to use while reading small letters found in a dictionary?",
    options: ["A) A convex lens of focal length 50 cm", "B) A concave lens of focal length 50 cm", "C) A convex lens of focal length 5 cm", "D) A concave lens of focal length 5 cm"],
    answer: "C) A convex lens of focal length 5 cm",
    explanation: "A convex lens of shorter focal length gives higher magnification (P = 1/f) when held close to the text.",
  },

  // =========================================================================
  // 10. THE HUMAN EYE AND THE COLOURFUL WORLD (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The least distance of distinct vision for a young adult with normal vision is about:",
    options: ["A) 25 m", "B) 2.5 cm", "C) 25 cm", "D) 2.5 m"],
    answer: "C) 25 cm",
    explanation: "The near point of a normal human eye is 25 cm, while the far point is at infinity.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "Why does the clear sky appear blue during daytime?",
    options: null,
    answer: "Molecules of air and fine particles in the atmosphere scatter sunlight. According to Rayleigh's scattering law, scattering is inversely proportional to λ⁴. Blue light has shorter wavelength than red light and is scattered much more strongly across the sky.",
    explanation: "Rayleigh scattering intensity I ∝ 1/λ⁴ causing short blue wavelengths to scatter widely across the sky.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "Twinkling of stars is due to atmospheric:",
    options: ["A) Dispersion of light", "B) Total internal reflection", "C) Refraction of light by varying air layers", "D) Scattering of light"],
    answer: "C) Refraction of light by varying air layers",
    explanation: "Starlight enters Earth's atmosphere and undergoes continuous refraction through air layers of fluctuating densities and refractive indices.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Why does the Sun appear reddish early in the morning and at sunset, but white at noon?",
    options: null,
    answer: "At sunrise/sunset, sunlight travels through a thicker layer of atmosphere and a longer distance. Blue and shorter wavelengths are scattered away, and only longer red wavelengths reach our eyes.\nAt noon, sunlight travels a shorter distance; very little scattering occurs, so the Sun appears white.",
    explanation: "Atmospheric optical path length variation modulating Rayleigh wavelength attenuation.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "A person with a myopic eye cannot see objects beyond 1.2 m distinctly. What should be the type and power of the corrective lens to restore proper vision?",
    options: null,
    answer: "Concave lens; Power = -0.83 D",
    explanation: "For myopic eye: u = -∞, v = -1.2 m = -120 cm. 1/f = 1/v - 1/u = -1/1.2 - 0 = -1/1.2 => f = -1.2 m. Power P = 1/f = 1/(-1.2) = -0.83 D (concave lens).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is hypermetropia (farsightedness)? State its two main causes.\n(b) How is hypermetropia corrected? Draw ray diagrams showing (i) hypermetropic eye, (ii) its correction using a suitable lens.\n(c) The near point of a hypermetropic eye is 1 m. Find the power of the lens required to read a book held at 25 cm.",
    options: null,
    answer: "(a) Hypermetropia is a vision defect where a person can see distant objects clearly but cannot see nearby objects distinctly. Causes: (1) Focal length of eye lens is too long, (2) Eyeball has become too short.\n(b) Corrected by a convex lens of suitable power.\n(c) u = -25 cm = -0.25 m, v = -1 m. 1/f = 1/v - 1/u = 1/(-1) - 1/(-0.25) = -1 + 4 = +3 D. Power = +3.0 D (Convex lens).",
    explanation: "Vision refraction defect physics, ciliary muscle insufficiency, and convergent corrective optics.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Explain the formation of a rainbow in the sky with the help of a ray diagram.\n(b) What is dispersion of white light? Name the component of white light that deviates the least and the most when passing through a glass prism.",
    options: null,
    answer: "(a) Tiny suspended raindrops act like small glass prisms. Sunlight entering a water droplet undergoes: (1) Refraction and dispersion at front surface, (2) Internal reflection at back surface, (3) Refraction out of droplet into observer's eyes, producing a spectrum.\n(b) Dispersion is the splitting of white light into its component seven colours (VIBGYOR). Red light deviates the least (longest wavelength); Violet light deviates the most (shortest wavelength).",
    explanation: "Refractive dispersion, internal reflection, and Snell-Cauchy dispersion in atmospheric water droplets.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "The Human Eye and the Colourful World",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The change in focal length of an eye lens to focus objects at different distances is brought about by the action of:",
    options: ["A) Pupil", "B) Retina", "C) Ciliary muscles", "D) Iris"],
    answer: "C) Ciliary muscles",
    explanation: "Accommodation is achieved by ciliary muscles altering the curvature and focal length of the crystalline lens.",
  },

  // =========================================================================
  // 11. ELECTRICITY (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The SI unit of electric potential difference is:",
    options: ["A) Ampere", "B) Volt", "C) Ohm", "D) Watt"],
    answer: "B) Volt",
    explanation: "1 Volt = 1 Joule / 1 Coulomb (V = W/Q).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State Ohm's law. What is the condition under which it is strictly valid?",
    options: null,
    answer: "Ohm's Law: The electric current flowing through a metallic conductor is directly proportional to the potential difference across its ends (V = IR), provided its temperature and other physical conditions remain constant.",
    explanation: "Linear voltage-current proportionality in ohmic conductors at constant temperature.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "A cylindrical conductor of length l and uniform area of cross-section A has resistance R. Another conductor of length 2l and resistance R of the same material has area of cross-section:",
    options: ["A) A/2", "B) 3A/2", "C) 2A", "D) 3A"],
    answer: "C) 2A",
    explanation: "R = ρl/A. For second wire, R = ρ(2l)/A' = R => ρ(2l)/A' = ρl/A => A' = 2A.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "An electric lamp of resistance 20 Ω and a conductor of 4 Ω resistance are connected in series to a 6 V battery. Calculate: (a) the total resistance of the circuit, (b) the current through the circuit, (c) the potential difference across the electric lamp.",
    options: null,
    answer: "(a) Total resistance R = 24 Ω\n(b) Current I = 0.25 A\n(c) Potential difference across lamp V = 5 V",
    explanation: "(a) R = 20 + 4 = 24 Ω. (b) I = V/R = 6/24 = 0.25 A. (c) V_lamp = I × R_lamp = 0.25 × 20 = 5 V.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Show how you would connect three resistors, each of resistance 6 Ω, so that the combination has a resistance of: (i) 9 Ω, (ii) 4 Ω.",
    options: null,
    answer: "(i) Two in parallel connected in series with the third: (6 × 6)/(6 + 6) + 6 = 3 + 6 = 9 Ω.\n(ii) Two in series connected in parallel with the third: (12 × 6)/(12 + 6) = 72/18 = 4 Ω.",
    explanation: "Equivalent resistance calculations for mixed series-parallel network topologies.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) State Joule's law of heating and derive the formula H = I²Rt.\n(b) An electric heater rated 1000 W operates 2 hours daily. An electric refrigerator rated 400 W operates 10 hours daily. What is the cost of energy to operate them for 30 days at ₹ 5.00 per kWh?",
    options: null,
    answer: "(a) Joule's law: Heat produced in a resistor is directly proportional to the square of current (I²), resistance (R), and time (t): H = VIt = (IR)It = I²Rt.\n(b) Heater daily energy = 1000 W × 2 h = 2 kWh. Refrigerator daily energy = 400 W × 10 h = 4 kWh. Total daily = 6 kWh. 30-day energy = 6 × 30 = 180 kWh. Total cost = 180 × ₹ 5 = ₹ 900.",
    explanation: "Thermodynamic Joule heating derivation and domestic electrical power consumption cost calculation.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Deduce the expression for the equivalent resistance of three resistors R₁, R₂, R₃ connected in parallel.\n(b) Why is a parallel arrangement preferred over series connection for domestic household circuits?",
    options: null,
    answer: "(a) In parallel, V is same across all resistors. Total current I = I₁ + I₂ + I₃. By Ohm's law, I = V/R_p, so V/R_p = V/R₁ + V/R₂ + V/R₃ => 1/R_p = 1/R₁ + 1/R₂ + 1/R₃.\n(b) Advantages: (1) Each appliance gets full mains voltage (220 V), (2) Each appliance can be switched on/off independently without affecting others, (3) If one appliance fails, the circuit is not broken, (4) Overall resistance decreases, allowing sufficient current draw.",
    explanation: "Kirchhoff current law parallel circuit derivation and domestic electrical engineering advantages.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Electricity",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Commercial unit of electrical energy (1 kWh or 1 'unit') in Joules is equal to:",
    options: ["A) 3.6 × 10⁵ J", "B) 3.6 × 10⁶ J", "C) 3.6 × 10⁴ J", "D) 36 × 10⁶ J"],
    answer: "B) 3.6 × 10⁶ J",
    explanation: "1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ Joules.",
  },

  // =========================================================================
  // 12. MAGNETIC EFFECTS OF ELECTRIC CURRENT (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "The magnetic field inside a long straight current-carrying solenoid is:",
    options: ["A) Zero", "B) Decreases as we move towards its end", "C) Increases as we move towards its end", "D) Uniform and the same at all points"],
    answer: "D) Uniform and the same at all points",
    explanation: "The field lines inside a solenoid are parallel straight lines, indicating that the magnetic field is uniform throughout the interior.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State Right-Hand Thumb Rule to find the direction of the magnetic field associated with a current-carrying conductor.",
    options: null,
    answer: "Imagine holding a straight current-carrying conductor in your right hand such that your thumb points in the direction of electric current. Then your curled fingers encircling the conductor will point in the direction of the magnetic field lines.",
    explanation: "Maxwell's corkscrew / Right-Hand Thumb Rule for circular magnetic field vectors.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "According to Fleming's Left-Hand Rule, the forefinger, middle finger and thumb represent respectively:",
    options: ["A) Magnetic field, Current, Force (Motion)", "B) Current, Magnetic field, Force", "C) Force, Magnetic field, Current", "D) Motion, Current, Magnetic field"],
    answer: "A) Magnetic field, Current, Force (Motion)",
    explanation: "Forefinger = Magnetic Field (B), Middle finger = Current (I), Thumb = Force/Motion (F).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is an electromagnet? List two ways to increase the magnetic strength of an electromagnet.",
    options: null,
    answer: "An electromagnet is a temporary magnet formed by placing a soft iron core inside a current-carrying solenoid coil.\nWays to increase strength: (1) Increase the magnitude of electric current flowing through the coil, (2) Increase the number of turns of insulated copper wire per unit length.",
    explanation: "Ferromagnetic core magnetization and Ampere circuital field enhancement.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Why do two magnetic field lines never intersect each other? Explain with physical reasoning.",
    options: null,
    answer: "If two magnetic field lines were to intersect at a point, a compass needle placed at that intersection point would point in two different directions simultaneously at the same time, which is physically impossible. Hence, field lines never cross.",
    explanation: "Uniqueness of tangent magnetic vector direction at any spatial coordinate.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) What is the function of an earth wire in domestic electrical circuits? Why is it necessary to earth metallic appliances?\n(b) Differentiate between short-circuiting and overloading.\n(c) What is the role of an electric fuse?",
    options: null,
    answer: "(a) Earth wire (green insulation) provides a low-resistance conducting path for leakage current to the ground. If insulation fails, metal casing current discharges safely to earth, blowing fuse and preventing fatal electric shocks.\n(b) Short-circuiting occurs when live wire and neutral wire come in direct contact due to damaged insulation, causing near-zero resistance and huge surge in current. Overloading occurs when total current drawn by many appliances connected simultaneously exceeds circuit rating.\n(c) A fuse is a safety device with a low melting point wire that melts and breaks the circuit during excessive current.",
    explanation: "Domestic electrical safety mechanisms: grounding, overcurrent protection, and fuse thermal tripping.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "Explain the phenomenon of electromagnetic induction discovered by Faraday. Describe two different laboratory methods to induce current in a coil.",
    options: null,
    answer: "Electromagnetic induction is the process of generating an induced electric current in a closed circuit by changing the magnetic flux linked with it.\nMethods: (1) Moving a bar magnet rapidly into and out of a stationary solenoid coil connected to a galvanometer. (2) Placing two coils (Primary and Secondary) close together and continuously switching current on/off in the Primary coil, which induces a current in the Secondary coil.",
    explanation: "Faraday's Law of Induction and mutual inductance between coupled coils.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Magnetic Effects of Electric Current",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "At the time of short circuit, the current in the circuit:",
    options: ["A) Reduces substantially", "B) Does not change", "C) Increases heavily", "D) Varies continuously"],
    answer: "C) Increases heavily",
    explanation: "Direct contact between live and neutral wires drops resistance close to zero, causing current to spike drastically.",
  },

  // =========================================================================
  // 13. OUR ENVIRONMENT (+8 Questions)
  // =========================================================================
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "Which of the following constitutes a food chain?",
    options: ["A) Grass, wheat and mango", "B) Grass, goat and human", "C) Goat, cow and elephant", "D) Grass, fish and goat"],
    answer: "B) Grass, goat and human",
    explanation: "Grass (Producer) → Goat (Primary consumer / Herbivore) → Human (Secondary consumer / Omnivore).",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "EASY",
    type: "SHORT_ANSWER",
    marks: 2,
    question: "State the 10 percent law of energy transfer in an ecosystem proposed by Lindeman.",
    options: null,
    answer: "According to Lindeman's 10% law, only 10% of the energy entering a particular trophic level is available for transfer to the next higher trophic level. The remaining 90% is lost as metabolic heat, respiration, and life processes.",
    explanation: "Thermodynamic energy dissipation across successive ecological trophic levels.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "MEDIUM",
    type: "MCQ",
    marks: 1,
    question: "Depletion of the ozone layer in the stratosphere is primarily caused by:",
    options: ["A) Chlorofluorocarbons (CFCs)", "B) Carbon monoxide", "C) Methane", "D) Sulphur dioxide"],
    answer: "A) Chlorofluorocarbons (CFCs)",
    explanation: "CFCs release reactive chlorine free radicals under UV radiation which catalytically break down O₃ molecules into O₂.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "MEDIUM",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "What is biological magnification? Explain with an example why top carnivores are most adversely affected.",
    options: null,
    answer: "Biological magnification is the progressive increase in the concentration of non-biodegradable harmful chemicals (e.g. pesticides like DDT) at successive trophic levels of a food chain.\nSince these chemicals are not metabolised or excreted, they accumulate progressively up the food chain, reaching maximum lethal concentration in top carnivores/humans.",
    explanation: "Trophic bioaccumulation of lipophilic xenobiotics along aquatic/terrestrial food chains.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "HARD",
    type: "SHORT_ANSWER",
    marks: 3,
    question: "Why are decomposers crucial for maintaining ecological balance? What would happen if all decomposers were eliminated from Earth?",
    options: null,
    answer: "(1) Decomposers (bacteria and fungi) break down complex organic remains of dead plants and animals into simple inorganic nutrients.\n(2) They recycle essential nutrients back into soil, air, and water for reabsorption by producers.\n(3) Without decomposers, Earth would be buried under heaps of dead organic debris and biogeochemical nutrient cycles would completely halt.",
    explanation: "Biogeochemical nutrient cycling and saprophytic organic recycling.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "HARD",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) How is ozone formed in the upper atmosphere? Write the chemical reactions involved.\n(b) Why is ozone layer vital for life on Earth?\n(c) What steps have been taken internationally to limit ozone depletion?",
    options: null,
    answer: "(a) High-energy UV radiation splits molecular oxygen: O₂ —UV→ O + O. Nascent oxygen combines with molecular oxygen: O + O₂ → O₃ (Ozone).\n(b) Ozone absorbs harmful UV-B radiation, protecting living organisms from skin cancer, cataract, and immune suppression.\n(c) In 1987, the United Nations Environment Programme (UNEP) forged the Montreal Protocol, freezing and phasing out CFC manufacturing and consumption globally.",
    explanation: "Chapman photochemical cycle of stratospheric ozone synthesis and international environmental treaties.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "MEDIUM",
    type: "LONG_ANSWER",
    marks: 5,
    question: "(a) Differentiate between biodegradable and non-biodegradable wastes with two examples each.\n(b) Describe three effective methods for eco-friendly solid waste management in urban areas.",
    options: null,
    answer: "(a) Biodegradable: Decomposed by biological micro-organisms into simple non-toxic substances (e.g. fruit peels, paper, cow dung). Non-biodegradable: Cannot be broken down by biological action and persist in environment causing pollution (e.g. plastics, glass, DDT).\n(b) Methods: (1) Segregation at source into wet and dry waste, (2) Composting of organic kitchen waste, (3) Recycling plastics, glass, and metals, (4) Biogas generation from sewage and agricultural waste.",
    explanation: "Waste classification, microbial enzyme specificity, and integrated municipal waste management.",
  },
  {
    board: "CBSE",
    grade: "CLASS_10",
    subject: "SCIENCE",
    topic: "Our Environment",
    difficulty: "EASY",
    type: "MCQ",
    marks: 1,
    question: "In a terrestrial ecosystem, what percentage of the energy of sunlight that falls on green leaves is converted into food energy by photosynthesis?",
    options: ["A) 1%", "B) 10%", "C) 50%", "D) 100%"],
    answer: "A) 1%",
    explanation: "Green plants capture only about 1% of the total solar energy incident on their leaves and convert it into chemical food energy.",
  },
];
